### ISSUE TITLE
Lỗi - Admin, Report XM3 4750 không lấy được mã DỊCH VỤ khi cho Vật tư kèm theo

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitaladmin#103]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Đa Khoa TPCT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbtpct_vtkt_noitru`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/rteRyBUfs)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019137003` - _**MaKB**_: `2407029197` - _**MaBA**_: `023612` _**NgayKCB**_: `25/07/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `22` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SA7.V24.0726.113236` - _**NgayHD**_: `25/07/2024` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `NO447` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`
Bệnh nhân có chỉ định CLS với mã NO447 kèm theo toa vật tư số hóa đơn  SA7.V24.0726.113236 nhưng chỉ có Mã hàng hóa ST259 khi xem XML3 Trên Admin và trên Report 130 là lấy được mã dịch vụ. Các hàng hóa khác cho cùng hóa đơn không lấy được mặc dù có check thanh bhyt

Hai Chứng từ cho Vật tư kèm theo tại Treatment
![image](https://github.com/user-attachments/assets/373657e3-0696-4304-89bc-cca403e76162)
![image](https://github.com/user-attachments/assets/a013b679-6e6c-41c5-8449-450ad7767c4a)

Report xuất XML3 theo 4210 thì lấy đầy mã dịch vụ như hình dưới
![image](https://github.com/user-attachments/assets/96e1e895-d77d-4170-847d-c1858e183ae8)

Hình khi xem XML3 tại Admin và Report theo QĐ 130 (4750)
![image](https://github.com/user-attachments/assets/1400fe42-712b-4791-9395-40f98c813822)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1008.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410080-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410080-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410080-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - Admin, Report XM3 4750 không lấy được mã DỊCH VỤ khi cho Vật tư kèm theo**

- 🐛: ***Chỉnh lỗi: XML03.MA_DICH_VU, XML03.TEN_DICH_VU thiếu đối với những VTYT đánh theo CLS,DV*** ![](https://i.imgur.com/SkH5ZCH.png)

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/103

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận** 
- Report và Admin đã lấy XML3 đúng

![image](https://github.com/user-attachments/assets/5ae8895e-75dd-4e16-af80-5514b8c21f74)
