### ISSUE TITLE
Lỗi - Services gửi checkin lỗi không lấy được mã  DV, mã Thuốc, mã VTYT và khi gửi được 1 lúc thì báo gửi không thành công rồi treo không gửi tiếp

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaladmin#104]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `93102`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Số 10**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_so10_loicheckin_guitudong_09102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/QgxIwcUHJ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019020797` - _**MaKB**_: `2410005581` - _**MaBA**_: `MaBA` _**NgayKCB**_: `09/10/2024` - _**MaPhong**_: `28` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Lỗi Services gửi checkin thiếu mã dịch vụ, mã thuốc, mã VTYT
![](https://i.imgur.com/wE3JocP.png)

2. Lỗi Services gửi được 1 lúc thì báo lỗi gửi không thành công rồi không gửi được tiếp treo phải tắt mở lại mới gửi tiếp
![](https://i.imgur.com/itpM8Od.png)

3. Admin xem Checkin thì thiếu mã dịch vụ, mã thuốc, mã VTYT nhưng xuất ra file XML thì có
![](https://i.imgur.com/HON1l3r.png)
![](https://i.imgur.com/y5vFuQE.png)
![](https://i.imgur.com/41sck80.png)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-10-15**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalServices.exe v.3.24.1011.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalServicesexe%2F32410110-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalServicesexe%2F32410110-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalServicesexe%2F32410110-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - Services gửi checkin lỗi không lấy được mã  DV_**

- ✨: Thực hiện theo mô tả [XML130/Hau-gui-checkin-xml.md](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/Hau-gui-checkin-xml.md)

- 🐛: Chỉnh lỗi khi gửi thành công chỉ set checkin_cls = 1, checkin_thuoc=1, checkin_vtyt=1 (nếu có)

- 🐛: Kiểm tra nếu MA_DICH_VU, MA_VAT_TU, MA_THUOC có mới thực hiện gửi. ***Tránh lỗi*** ![](https://i.imgur.com/q1385Ty.png)

- ✨: ***Xử lý ghi nhận lỗi khi gửi API, nếu hồ sơ, checkin gửi lỗi quá 20 lần, sẽ không gửi hồ sơ, checkin này nữa.***

- ✨: ***Lưu ý: Cập nhật cấu trúc*** ![](https://i.imgur.com/0QT8JzM.png)

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/104

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalServices.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '18/10/2024'.
***
- Đã gửi cho đơn vị kiểm tra theo dõi tiến trình gửi (do không test gửi được), phối hợp đơn vị kiểm tra và chờ phản hồi từ đơn vị gửi

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalServices.exe v.3.24.1011.1 
***
### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Có hồ sơ check in gửi lỗi 20 lần được bị ẩn đi nhưng phần mềm không gửi tiếp các hồ sơ còn lại trên danh sách
  - Trường hợp BV báo gửi lỗi hồ sơ check in danh sách hồ sơ gửi có 100 hồ sơ thì không gửi tiếp

- Hình ảnh lỗi:

![](https://i.imgur.com/T5P6x6T.png)
![](https://i.imgur.com/TaUAGce.png)

- Data: 
  - tra_so10_loiguixmltudong_14102024
  - tra_so10_loiguixmltudong_102024_14102024

***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @chauthanhtra  </sub>

- ***Nhờ kiểm tra lại tài khoản lại hoặc IP cổng giám định, vì thấy đa số là lỗi không thể lấy phiên làm việc*** ![](https://i.imgur.com/G5Kicd0.png)

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ**
***
- File hồ sơ vẫn gửi lên cổng được bình thường nha anh, có thiếu hồ sơ nhưng vẫn gửi lên được  nên có thể cổng không ổn định nhưng vẫn gửi lên được -> không phải do tài khoản hoặc IP vì nếu do tài khoản hoặc IP thì file hồ sơ KCB cũng không gửi được . Trường hợp này là không gửi được checkin thôi
- BV báo gửi hồ sơ KCB nhiều hồ sơ gửi bị lỗi này, xem trên Admin thi không lỗi
![](https://i.imgur.com/th5rhuh.png)
  - Malk: 93102_2024_10_2024037952_2410008916
  - Data: tra_so10_loiguixmltudong_102024_14102024
![](https://i.imgur.com/xDn00zV.png)

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @chauthanhtra  </sub>

- Lỗi không có chẩn đoán chính, có thể lúc gửi Hồ sơ thì đang trả về điều trị hoặc mở khóa chứng từ. Trường hợp này Tổ Lập trình sẽ thực hiện lại, nếu không có mã này sẽ không gửi hồ sơ, và không đưa vào danh sách lỗi, để có thể gửi lại những hồ sơ này.
- Trường hợp lỗi không lấy được Token (PHIÊN LÀM VIỆC) nhờ Khách hàng theo dõi thêm, hoặc remote theo dõi theo hướng này, những trường hợp không gửi được, thì ngưng Services 1 khoảng thời gian, rồi xóa dấu hiệu hồ sơ lỗi 20 lần về bằng 0, rồi mở Services lại, xem những hồ sơ này có gửi lại được hông. Chỗ này đang nghi ngờ là do Services gửi nhiều hồ sơ trong khoảng thời gian ngắn nên Cổng hông cho phép. Nhờ @chauthanhtra theo dõi giúp em, để Tổ lập trình tìm giải pháp khác.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalServices.exe v.3.24.1011.1
***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Khi Services gửi được 1 lúc thì không gửi lên được nữa phải tắt Services mở lại thì gửi lên được liền, chỉnh số lần gửi cũng gửi lại được
  - Nhiều hồ sơ gửi lỗi 20 lần nhưng không có ghi nhận lỗi
- Hình ảnh lỗi:

Clip tắt Services mở lại để gửi: https://gofile.me/78TQg/3UzfF5xVp

Ảnh ghi lỗi
![](https://i.imgur.com/iV6BDlv.png)

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @chauthanhtra  </sub>

- Theo dõi hỗ trợ Tổ lập trình là khoảng thời gian từ lúc gửi được đến lúc không gửi được là bao lâu.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalServices.exe v.3.24.1011.1
***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Test trực tiếp ở PK Minh Quang thì sau khoản 15 phút thì Services không gửi được

- Hình ảnh lỗi:

![](https://i.imgur.com/oRieOlz.png)
![](https://i.imgur.com/oHJPINQ.png)
![](https://i.imgur.com/oHJPINQ.png)

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @chauthanhtra  </sub>

- Thanks nhiều
- Tổ Lập trình sẽ tìm cách xử lý với những thông tin trên

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalServices.exe v.3.24.1021.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalServicesexe%2F32410210-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalServicesexe%2F32410210-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalServicesexe%2F32410210-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - Services gửi checkin lỗi không lấy được mã  DV_**

- 🐛: ***Thêm chức năng chỉ gửi những hồ sơ khi XML01.CHAN_DOAN_RV khác rỗng, XML01.MA_BENH_CHINH (Tránh tình trạng Mở khóa, Trả về điều trị vẫn gửi hồ sơ) gây lỗi*** ![](https://i.imgur.com/X8QH4WV.png)

- 🐛: Xử lý lấy Token mỗi khi gửi hồ sơ, xử lý trường hợp gửi được một thời gian là bị lỗi, phải tắt mở lại.

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/104

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalServices.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @chauthanhtra

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '28/10/2024'.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalServices.exe v.3.24.1021.0
***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Services mới hoàn toàn không gửi được hồ sơ nào hết cả checkin và hồ sơ KCB. mở lên vào gửi là báo gửi không thành công
- Hình ảnh lỗi:
![UltraViewer_Desktop_dOx2BaTPTg](https://github.com/user-attachments/assets/95a0afe8-fb96-4a7d-a0a8-1bfda2cf50cb)



Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @chauthanhtra  </sub>

- Tổ Lập trình kiểm tra lại.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalServices.exe v.3.24.1022.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalServicesexe%2F32410220-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalServicesexe%2F32410220-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalServicesexe%2F32410220-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - Services gửi checkin lỗi không lấy được mã  DV_**

- 🐛: ***Thêm chức năng chỉ gửi những hồ sơ khi XML01.CHAN_DOAN_RV khác rỗng, XML01.MA_BENH_CHINH (Tránh tình trạng Mở khóa, Trả về điều trị vẫn gửi hồ sơ) gây lỗi*** ![](https://i.imgur.com/X8QH4WV.png)

- 🐛: Xử lý lấy Token mỗi khi gửi hồ sơ, xử lý trường hợp gửi được một thời gian là bị lỗi, phải tắt mở lại.

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/104

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalServices.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '29/10/2024'.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalServices.exe v.3.24.1022.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Phần mềm Services đã fix được lỗi bị treo Services không gửi được hồ sơ checkin và hồ sơ KCB khi phần mềm hoạt động được 1 lúc.
  - Đã fix Lỗi Services gửi checkin thiếu mã dịch vụ, mã thuốc, mã VTYT. hiện tại chưa phát hiện lại lỗi này
  - Chưa kiểm tra được nội dung Services gửi tự động có đúng không, chưa có công cụ để kiểm tra nội dung gửi tự động và chức năng xác nhận bệnh nhân có gửi được checkin hay chưa nên chưa đối chiếu được dữ liệu Admin gửi và Services gửi. nếu có lỗi mới sẽ báo git khác.

- Hình ảnh: 
![](https://i.imgur.com/J0fKTAS.png)
![](https://i.imgur.com/UPQDGjI.png)
![](https://i.imgur.com/saRPyka.png)
![](https://i.imgur.com/Jt9udfK.png)
![](https://i.imgur.com/ERRGO9y.png)




***

> ### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**
> 
> - Diễn giải lỗi:
> 
> - Hình ảnh lỗi:
> 
> 

***
> Hình ảnh Phiếu 01, 02, xuất XML.
> Nhập thuốc -> xuất thuốc -> tổng hợp.
> Hình ảnh chứng mình cho việc kiểm tra này.
> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
> ***
> Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.
