### ISSUE TITLE
Lỗi - Chức năng xuất xml4750 sai ngày thanh toán giữa danh sách hồ sơ và ngày thanh toán của xml

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#105]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhbinh_xml4750_09102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_thanhbinh_xml4750_09102024`](https://gofile.me/78TQg/I1TmBpRW3)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024003929` - _**MaKB**_: `2409009940` - _**MaBA**_: `2024007437` _**NgayKCB**_: `01/10/2024 10:17:00 SA` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `05` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân có ngày ra viện 01/10/2024
- chức năng xuất xml 4750 load danh sách không đúng theo ngày ra viện.
- Ngày thanh toán giữa danh sách XML không đúng so với XML1

```
![ảnh](https://github.com/user-attachments/assets/4d2bbfb8-29fa-40e5-bc8e-3beabedb8418)
![ảnh](https://github.com/user-attachments/assets/53071ab8-af8a-49a4-aebc-a36fc37844df)
![ảnh](https://github.com/user-attachments/assets/2eedddbc-cc70-44a1-b96d-f0ecd898b525)
![ảnh](https://github.com/user-attachments/assets/45101375-83c0-4ae5-8ccc-8f38f911c21a)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-10-20**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @le-an-87 
- Với phiên bản Reports mới nhất, dùng chức năng xử lý Kiểm tra chi phí để chỉnh hồ sơ này lại.
- Các phiên bản mới cập nhật có kiểm soát phần sai này, nhờ @le-an-87 theo dõi tiếp nhé.
- ![](https://i.imgur.com/xNNAsM5.png) ![](https://i.imgur.com/cVm2fJN.png)

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
## 
***
> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:
- Hình ảnh lỗi:
> ✅  Hình ảnh chứng mình cho việc kiểm tra này.
Chức năng cập nhật đã fix được lỗi.
![ảnh](https://github.com/user-attachments/assets/1a3ebd96-d4f3-4045-a9df-ebfa1bdad0a8)

> 📘 Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
