### ISSUE TITLE
Xuất XML thiếu mã BS thực hiện CLS.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#13]
CLS mà có chỉ định những CLS(CĐHA, XN, TDCN) có thực hiên trên phần mềm nhưng khi xuất XML  trong bảng 3 cột MA_BACSI thì nó không lấy lên được mã của BS thực hiện những cls đó, report thì lấy được.
Data: binh_ph_hoabinh_st_xmlthieumabs
Mã khám bệnh: 2205000404
![image](https://user-images.githubusercontent.com/99630883/170170277-de8f1a9d-26d1-4811-b9b0-4c85f3ad2b4e.png)
![image](https://user-images.githubusercontent.com/99630883/170170442-cb163766-14ff-4cdf-a6b1-ff58fb2fca33.png)
![image](https://user-images.githubusercontent.com/99630883/170170522-11985516-778c-4883-aaca-4a96fb36c3e7.png)
![image](https://user-images.githubusercontent.com/99630883/170170555-24661ddb-09c5-48f4-a46a-3ef1429c4a95.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitaladmin/commit/6d39e18deca197c01fd8047d10a08c0821508364
Hiện tại sẽ fix lỗi lấy sai thông tin nhân viên thực hiện, không thực hiện nối mã nhân viên thực hiện và nhân viên chỉ định.
