### ISSUE TITLE
BV Nhi Đồng CT - XML Gửi tự động bệnh án ngoại trú không lấy được dữ liệu thủ thuật - XML5

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#14]
Bệnh có lập phiếu thủ thuật nhưng xml 5 không lấy được dữ liệu
tên data: bi_nhidong_n2022001542
maba: N2022001542
![image](https://user-images.githubusercontent.com/96155021/170215672-f6e99f15-0a80-4511-8b28-1687f5573dc9.png)
![image](https://user-images.githubusercontent.com/96155021/170215716-74edaff4-759e-43d8-9ef2-cc3b768607f6.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
![image](https://user-images.githubusercontent.com/58720300/170219137-62a3ed60-acfb-4c9b-95fa-6b38e86a7dae.png)
![image](https://user-images.githubusercontent.com/58720300/170219170-1c390a8e-5390-43a6-99d6-a274a5867cc6.png)

**Comment by nghibi** [comment]
@o-ngtrieuhau861gmailcom này thanh toán đợt theo id chứ:
![image](https://user-images.githubusercontent.com/91751241/170222896-23dc642c-38bf-4a0d-b837-5ffc08eff524.png)
![image](https://user-images.githubusercontent.com/91751241/170222982-97301c28-b45b-4662-bb1d-9da3680a4a09.png)
![image](https://user-images.githubusercontent.com/91751241/170223081-9b2e0df2-9cd4-4bcb-b14c-8c6f96f6344b.png)

**Comment by nghibi** [comment]
này là bệnh án ngoại trú thanh toán ngày nha

**Comment by nghibi** [comment]
Chỗ này sao rồi @o-ngtrieuhau861gmailcom

**Comment by o-ngtrieuhau861gmailcom** [comment]
Hiện tại phần bệnh án ngoại trú thanh toán ngày xem như là bệnh nhân ngoại trú nên không có load mã bệnh án để xử lý, đề nghị thay đổi mô tả lại bỏ những phần liên quan tới mã bệnh án trong [mô tả này](https://github.com/oth-dhghospital/dhg.hospitaladmin/blob/main/MoTaThayDoi/Vinh%20-%20Mo%20ta%20cot%20%5Bdien_bien%5D%20%5Bhoi_chan%5D%20va%20%5Bphau_thuat%5D%20XML5.pdf)
![image](https://user-images.githubusercontent.com/58720300/171556055-8d13bf86-e334-4d82-bf6c-ea3c1ba4b7c4.png)

**Comment by nghibi** [comment]
Cập nhật theo mô tả:
[Vinh - Mo ta cot [dien_bien] [hoi_chan] va [phau_thuat] XML5 - 20220602.1.pdf](https://github.com/oth-dhghospital/dhg.hospitaladmin/files/8821697/Vinh.-.Mo.ta.cot.dien_bien.hoi_chan.va.phau_thuat.XML5.-.20220602.1.pdf)
