### ISSUE TITLE
Xuất XML3 lấy sai thông tin thời gian TT/PT.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#16]
KHi xuất XML, XML3 của các TT/PT đang lấy ngày giờ chỉ định ->sai so với quy định(Hình 1) -> BH đang xuất toán BV Thạnh Trị.
Đúng là phải lấy ngày giờ bắt đầu TT/PT trên form lập phiếu TT/PT(Hình 2).
Cả nội trú và ngoại trú đều bị.
Data: binh_dbthanhtri_14_06_2, maba: 2022003377

Hình 1
![image](https://user-images.githubusercontent.com/99630883/174019269-e670db36-caf5-4d12-bbdf-0c64a9880c29.png)

Hình 2.
![image](https://user-images.githubusercontent.com/99630883/174019088-35e6b4d6-b6f1-4879-8e6e-fe6551c11c38.png)

**Comment by nghibi** [comment]
Này chờ thống nhất anh mô tả lại cái nha.
