### ISSUE TITLE
Admin bị lỗi khi Tạo lập bộ bảng lưu trữ cắt bỏ dữ liệu trực tiếp qua cơ sở dữ liệu khác

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaladmin#17]
Alo anh @o-ngtrieuhau861gmailcom 
- Chức năng tạo lập bộ bảng lưu trữ khi kết chuyển dữ liệu khác CSDL bị lỗi
- Admin -> tiện ích -> Cắt bỏ dữ liệu ra CSDL lưu trữ -> Kết chuyển dữ liệu trực tiếp -> Tạo lập bộ bảng lưu trữ
![ảnh](https://user-images.githubusercontent.com/97272332/174236955-e3f06cc5-d85a-4bca-a6a1-04f1cc35550c.png)

Phiên bản :2022.06.15.061356AM
Npgsql.NpgsqlException:
column "hddtprefixfkey" specified more than once
Severity: ERROR
Code: 42701
   at HosAdmin.Forms.FrmKCDuLieuRaNgoai.btnCreateTable_Click(Object sender, EventArgs e)
 create table store.thuchi(soct varchar (20),loai varchar (10),khct varchar (20),ngayct timestamp without time zone ,mabn varchar (20),makb varchar (20),madt varchar (10),noitru numeric (1,0),madv varchar (20),maphong varchar (20),lydo varchar (1000),nguoigiao varchar (255),nguoinhan varchar (255),tongtien numeric (14,0),ptthu numeric (6,2),thucthu numeric (14,0),dain numeric (1,0),taikhoan varchar (20),tenmay varchar (10),xoa numeric (1,0),ngayxoa timestamp without time zone ,thangkt varchar (2),namkt varchar (4),quyen varchar (20),sobl varchar (20),thucthuct numeric (14,0),psmato varchar (10),psdabaocao varchar (20),tygia numeric (14,0),loaibldv numeric (1,0),miengiam numeric (14,0),thatthu numeric (14,0),soctbltong varchar (20),diachi varchar (250),masothue varchar (20),tendonvibn varchar (255),theodoi varchar (6),nammp varchar (4),thangmp varchar (2),ngaymp timestamp without time zone ,nhathuoc numeric (1,0),mienchitra_bh2 numeric (1,0),mienchitra numeric (1,0),psptthu numeric (4,0),tachhd varchar (50),solanin numeric (3,0),thucthutp numeric (14,0),phienban varchar (20),tamung numeric (14,0),thucthubh_bh2 numeric (14,0),tuoi numeric (3,0),psvanchuyen_bh2 numeric (1,0),thucthubh numeric (14,0),ptthu_bh2 numeric (3,0),thuesuat numeric (4,2),chuyenpt numeric (1,0),dvttuoi numeric (3,0),psvanchuyen numeric (1,0),chuyenptluu varchar (20),tachhd_ps numeric (10,0),lydo_thuong text ,lydo_dichvu text ,thucthu_thuong numeric (140,0),thucthu_dichvu numeric (140,0),hinhthucthanhtoan varchar (50),mgdongchitracls numeric (10,0),thucthu_dongchitracls numeric (140,0),thatthuchenhlech numeric (14,0),resulthddt varchar ,khct_hddt varchar (20),sobl_hddt varchar (20),quyen_hddt varchar (20),synchddt numeric (1,0),hddtprefixfkey varchar (200),hddtprefixfkey varchar (20),taikhoanthue varchar (30),thucthu_dichvunt numeric (14,0),nguonkhac numeric (14,2),filebytespdf varchar ,thuesuathddt numeric (2,0),lydo_dichvunt varchar ,matracuu_hddt varchar (200),thucthu_pay numeric (14,0),pay_payid varchar (200),loaikh numeric (1,0)); CREATE INDEX thuchi_idx ON store.thuchi USING btree (namkt, thangkt);

data test: tra_lethanh_full

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0704.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/dff93cb4c1ac4a1030e52547110dcf7bb1cbf6b5)

**Comment by chauthanhtra** [comment]
ok anh @ongtrieuhau
