### ISSUE TITLE
Lỗi - chức năng xem chi tiết trong form Thực hiện liên thông dược quốc gia không chạy được

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#20]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `60152`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Phúc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamphuc_duocquocgia`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [``](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**SoHD**_: `PN0822-14` - _**NgayHD**_: `03/08/2022` - _**ThangKT**_: `08` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Module admin khi vào chức năng Thực hiện liên thông dược quốc gia -> chọn xem chi tiết hóa đơn thì chương trình không chạy!
chức năng không có tác dụng!

Module Medicine chọn chức năng đó thì sinh ra lỗi!


```

Admin
![image](https://user-images.githubusercontent.com/96155021/183855669-e179f9d0-37a0-4bbb-b0b9-696ff3d91737.png)

chọn chức năng này bên Medicine thì sinh ra lỗi
![image](https://user-images.githubusercontent.com/96155021/183856031-5bbc7101-7366-4364-90e7-ade811debf56.png)

> **anh @nghivanbi ơi xem giùm em chổ Medicine luôn nhe anh!**

**Comment by le-an-87** [comment]
alo anh @nghivanbi , anh @ongtrieuhau ơi coi giùm em chổ này với anh!

**Comment by le-an-87** [comment]
alo anh @nghivanbi , anh @ongtrieuhau ơi coi giùm em chổ này với anh!

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0930.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/d889fb796fa84a0723fe84c79c26f1400fc359cb)

> `Module Medicine chọn chức năng đó thì sinh ra lỗi!` 

> **cập nhật dll mới** nhé @nghivanbi

**Comment by nghivanbi** [comment]
Cập nhật
Medicine: [v3.22.0930.1](http://www.fsend.vn/download/F0G07j71BUGGIWeyXLeI1HVwDyJJbg0c)

**Comment by le-an-87** [comment]
Medicine xem vẫn báo lỗi nhe anh!
![image](https://user-images.githubusercontent.com/96155021/193220959-e745b45f-a46a-4c54-a7dd-5396df88e7d3.png)

admin thì xem được rồi nhe anh!
![image](https://user-images.githubusercontent.com/96155021/193220823-116ae3a2-0ebe-4349-96c2-1f3d0585c64e.png)

**Comment by ongtrieuhau** [comment]
Check lại nhé @nghivanbi

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: onedrive.live.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr></td><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515</em></td><td><em> :date: 2022-11-18T03:55:37Z</em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: onedrive.live.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr></td><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515</em></td><td><em> :date: 18/11/2022 10:55:37</em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: onedrive.live.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr></td><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515</em></td><td><em> :date: 18/11/2022 10:55:37</em></td><td><em> :memo: kumcj</em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: onedrive.live.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr></td><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515</em></td><td><em> :date: 18/11/2022 10:55:37</em></td><td><em> :memo: wezmzhugoy1k</em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: onedrive.live.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr></td><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515</em></td><td><em> :date: 18/11/2022 10:55:37</em></td><td><em> :memo: 4d0f3df8</em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: onedrive.live.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr></td><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515</em></td><td><em> :date: 18/11/2022 10:55:37</em></td><td><em> :memo: dc66f911</em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:arrow_down: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: onedrive.live.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)** **[:arrow_down: api.onedrive.com](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBck5WMlBqU25WR0hic3FJRm14QXl2b2tJTkk/root/content)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr></td><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515</em></td><td><em> :date: 18/11/2022 10:55:37</em></td><td><em> :memo: dc66f911</em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:arrow_down: api.onedrive.com](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBck5WMlBqU25WR0hic3FJRm14QXl2b2tJTkk/root/content)** **[:arrow_down: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: onedrive.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr></td><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515</em></td><td><em> :date: 18/11/2022 10:55:37</em></td><td><em> :memo: dc66f911</em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:arrow_down: api.onedrive.com](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBck5WMlBqU25WR0hic3FJRm14QXl2b2tJTkk/root/content)** **[:arrow_down: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: onedrive.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515 </em></td><td><em> :date: 18/11/2022 10:55:37 </em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:arrow_down: api.onedrive.com](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBck5WMlBqU25WR0hic3FJRm14QXl2b2tJTkk/root/content)** **[:arrow_down: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: onedrive.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515 </em></td><td><em> :date: 18/11/2022 10:55:37 </em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:arrow_down: api.onedrive.com](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBck5WMlBqU25WR0hic3FJRm14QXl2b2tJTkk/root/content)** **[:arrow_down: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: onedrive.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515 </em></td><td><em> :date: 18/11/2022 10:55:37 </em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:arrow_down: api.onedrive.com](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBck5WMlBqU25WR0hic3FJRm14QXl2b2tJTkk/root/content)** **[:arrow_down: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: onedrive.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515 </em></td><td><em> :date: 18/11/2022 10:55:37 </em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:arrow_down: api.onedrive.com](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBck5WMlBqU25WR0hic3FJRm14QXl2b2tJTkk/root/content)** **[:arrow_down: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: onedrive.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515 </em></td><td><em> :date: 18/11/2022 10:55:37 </em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:arrow_down: api.onedrive.com](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBck5WMlBqU25WR0hic3FJRm14QXl2b2tJTkk/root/content)** **[:arrow_down: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: onedrive.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi https://github.com/dh-hos/dhg.hospitaladmin/issues/19 
 - Fix lỗi https://github.com/dh-hos/dhg.hospitaladmin/issues/20#issuecomment-1263275190 
- Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515 </em></td><td><em> :date: 18/11/2022 10:55:37 </em></td></tr></table></div>

**Comment by o22issue** [comment]
<div align="center"><img src="https://raw.githubusercontent.com/dh-hos/public-files/main/Logo/dhg-hos.ico" width=18></div>

:mega: **_Cập nhật_** :point_right: [**Setup-HospitalAdmin.v1.0.1108.42.zip**](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)

- Tập tin cài đặt tại: **[:arrow_down: api.onedrive.com](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBck5WMlBqU25WR0hic3FJRm14QXl2b2tJTkk/root/content)** **[:arrow_down: drive.google.com](https://drive.google.com/uc?id=1WueRPnZ4ehq1xPSgGkxmFV39svr3_fqB&export=download&confirm=t)** **[:link: fsend.vn](http://www.fsend.vn/download/JPcGjclQCKdDebsK78b6ZUspmNyZ_ew9)** **[:link: onedrive.com](https://studentssolano-my.sharepoint.com/personal/bk_students_solano_edu/_layouts/15/download.aspx?share=EWnGDOON4_REsPZ7T70KVYEBHtwjEozQ-fLcPKXq-sxvEA)**

:blue_book: **_Nội dung_** : 👇

 - Fix lỗi https://github.com/dh-hos/dhg.hospitaladmin/issues/19 
 - Fix lỗi https://github.com/dh-hos/dhg.hospitaladmin/issues/20#issuecomment-1263275190 
- Fix lỗi sai dữ liệu 
 - Không thực hiện được dữ liệu

<div align="right"><table><tr><td><em> :robot: WIN-JG1E0O7FSBS\codedh_othau </em></td><td><em> :briefcase: changesetId: #515 </em></td><td><em> :date: 18/11/2022 10:55:37 </em></td></tr></table></div>
