### ISSUE TITLE
Lỗi - Menu kiểm tra xuất XML load BN thu phí.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#21]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_xml_load_doituongthuphi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022010373` - _**MaKB**_: `MaKB` - _**MaBA**_: `2022006303` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `09` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Lúc nhập viện BN là đối tượng **BHYT**, sau khi nhập viện xong trong nội trú chỉnh đối tượng thành **Thu phí**, tất cả chi phí của BN đều thuộc đối tượng Thu phí, không có chi phí nào liên quan đến BHYT hết: bnnoitru.madt='06', chungtu.madt='06', chidinhcls='06'.
Nhưng khi xuất viện xong, trong Menu **Kiểm tra xuất XML** vẫn hiển thị tên BN đóm khi người dùng nhìn vào sẽ hiểu lầm là BHYT chưa được gửi cổng BHXH, gây khó khăn trong việc kiểm dữ liệu.

![image](https://user-images.githubusercontent.com/99630883/192970237-adfd9449-f8a7-4502-a2da-3f4a9deb538f.png)

**Comment by ongtrieuhau** [comment]
Trường hợp này xuất hiện là do lúc tạo XML để gửi BHXH, bệnh nhân có chi phí Bảo hiểm, sau đó mới xử lý đổi đối tượng. Cập nhật module Services mới sẽ hỗ trợ xóa những hồ sơ XML này.

Cập nhật: 
- Admin: [3.22.0929.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/696b2f9e35a25fe8feb2778aea89df99d0b699b8)
- Services: [3.22.0929.1](https://github.com/dh-hos/dhg.hospitalservices/commit/a2e7f7a2883c1f012f6bdf2408d4558b5af3660f)
