### ISSUE TITLE
Lỗi - XML gửi tự động đối với bn có check BN Lao không mã hóa lydo_vaovien = 7

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#23]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_bnlao`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022027890` - _**MaKB**_: `2210014368` - _**NgayKCB**_: `26/10/2022` - _**MaPhong**_: `53` - _**MaDV**_: `PVT` - _**ThangKT**_: `10` - _**NamKT**_: `2022`
   > _**KhoChan**_: `14` - _**KhoLe**_: `05`
###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Trường hợp bệnh nhân Lao nhưng không cho chẩn đoán Z22.7

Bệnh nhân có check BN Lao khi gửi tự động XML (ma_lydo_vvien = 4 và ma_loai_kcb = 1) không ghi nhận
ma_lydo_vvien = 7 và ma_loai_kcb = 7

-> Bệnh viện đề nghị chỉnh lại ma_lydo_vvien = 7 và ma_loai_kcb = 7 khi có check vào BN Lao
```
Lệch XML giữa Reports và Admin
![image](https://user-images.githubusercontent.com/96155021/197970333-dc5972aa-3f6f-42b8-8cc3-9c2fc6cd4771.png)

mô tả tt36
![image](https://user-images.githubusercontent.com/96155021/197970442-7fbf4ac0-e89b-453a-9f16-adb31833e245.png)

thông tin nhận bệnh
![image](https://user-images.githubusercontent.com/96155021/197970501-642c07a3-664d-47d4-bf0c-ec012377fcc8.png)

Form khám bệnh
![image](https://user-images.githubusercontent.com/96155021/197970574-f18493e7-d5d0-464b-8ecb-04d0d89e9542.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.1028.2](https://github.com/dh-hos/dhg.hospitaladmin/commit/ad317e9dbce895684286c4ac59e7bcd1bcb2fc57)

**Comment by ongtrieuhau** [comment]
Cập nhật Service [3.22.1028.1](https://github.com/dh-hos/dhg.hospitalservices/commit/18343d740e90c22a4a80a964b2ca3f167263a71c)

**Comment by le-an-87** [comment]
đã fix!
