### ISSUE TITLE
Yêu cầu - Thực hiện yêu cầu cấp Licence

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitaladmin#25]
https://github.com/dh-hos/Mo-ta-he-thong/issues/21

**Comment by ongtrieuhau** [comment]
Admin [3.22.1226.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/6ff56eec6e99c7dbde93b22f6541b6896c13ae65)
Fees [3.22.1226.1](https://github.com/dh-hos/dhg.hospitalfees/commit/8319905e25802fef1e229f181c298d74855af4be)
Printer [3.22.1226.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/9571cc6c238f12406a132506268d7d9d05ba6b4e)
