### ISSUE TITLE
Yêu cầu - Cấp key mới cho 87196 và 87197

### ISSUE THREAD

**Issue by ongtrieuhau** [dh-hos/dhg.hospitaladmin#27]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ông Triệu Hậu**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) 87196 và 87197
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Yêu cầu cấp key mới cho 2 mã bệnh viện 87196 và 87197
```
##### Chi tiết yêu cầu: 
[VV cap ma KCB CS 2 TTYT Thanh Binh.docx](https://github.com/dh-hos/dhg.hospitaladmin/files/10369888/VV.cap.ma.KCB.CS.2.TTYT.Thanh.Binh.docx)
[1. Vv dieu chinh ma CS KCB cua CS 2 huyen Lap Vo va Thanh Binh.docx](https://github.com/dh-hos/dhg.hospitaladmin/files/10369889/1.Vv.dieu.chinh.ma.CS.KCB.cua.CS.2.huyen.Lap.Vo.va.Thanh.Binh.docx)

**Comment by ongtrieuhau** [comment]
Cập nhật

- [Admin 3.23.0109.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/a3f740dfd4825511995d6e2b987a7684021f3906)
- [Printer 3.23.0109.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/fa1a281a2c2f087faa755a3681ec8ac20b1e789e)
- [Fees 3.23.0109.1](https://github.com/dh-hos/dhg.hospitalfees/commit/7a2771d407392ca0fb00133e6e165f5914d33687)
- [Thư viện hỗ trợ module khác](https://github.com/dh-hos/oLibraries/commit/3f68ce1ac8cb35b6442845c48b4644f6fb2bb419)

**Comment by nghivanbi** [comment]
1. Tên cơ sở khám chữa bệnh: Khoa Khám bệnh cơ sở 2 thuộc Trung tâm Y tế huyện Thanh Bình
Mã cơ sở Khám bệnh, chữa bệnh: 87196
2. Tên cơ sở khám chữa bệnh: Khoa Khám bệnh cơ sở 2 thuộc Trung tâm Y tế huyện Lấp Vò. 
Mã cơ sở Khám bệnh, chữa bệnh: 87197 
--> 87192 sở cấp sai

**Comment by ongtrieuhau** [comment]
Cập nhật 

- [Admin 3.23.0109.2](https://github.com/dh-hos/dhg.hospitaladmin/commit/83cda48787f90a4ddc3d02078b0bb37be1be687f)
- [Printer 3.23.0109.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/bf985455844aedb4882d1b198cab2d78c2f47a7f)
- [Fees 3.23.0109.2](https://github.com/dh-hos/dhg.hospitalfees/commit/f9a5f380858db5d44ce4f6370b8c9da63be8cd91)
- [Thư viện hỗ trợ](https://github.com/dh-hos/oLibraries/commit/8ce064c77125bd040ef429877faa2f9b77f24b5a)

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.23.0109.2](http://www.fsend.vn/download/wzUlaIoJ9QwzOsqk7RmA7PHk58s4aBdS)

**Comment by vuongdh** [comment]
Cập nhật:
Treatment: [2023.0109v2](http://www.fsend.vn/download/4R1PDZJdDkhUo-x1fYJ24do2qWnPaBRQ)

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230109](http://192.168.10.79:8090/Reports/SetupHospitalReport20230109.zip)
- [HospitalDiagnoseSetup20230109](http://192.168.10.79:8090/Diagnose/HospitalDiagnoseSetup20230109.zip)
- [HospitalLaboratorySetup20230109](http://192.168.10.79:8090/Labotory/HospitalLaboratorySetup20230109.zip)

Fshare:
- [SetupHospitalReport20230109](https://www.fshare.vn/file/K3HUJVJRWYU5)
- [HospitalDiagnoseSetup20230109](https://www.fshare.vn/file/A4HR6BROQFLG)
- [HospitalLaboratorySetup20230109](https://www.fshare.vn/file/CYH9MZV6WU61)
