### ISSUE TITLE
Yêu cầu - Bổ sung chức năng xuất xml tự động gửi lên cổng Sở y tế Đồng Tháp (87196 - cs2 bv Thanh Bình)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#28]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87196`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **CS2 BV Thanh Bình**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) ``
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [``](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
CS2 BV Thanh Bình - mabv: 87196

Đề nghị bổ sung chức năng xuất xml tự động khi kết thúc đợt điều trị!

```
![image](https://user-images.githubusercontent.com/96155021/216861463-f0ea45ba-5b10-4f19-a98f-1f05e5e24822.png)

**Comment by le-an-87** [comment]
01/04/2023!

**Comment by ongtrieuhau** [comment]
Cập nhật Services [3.23.0411.2](https://github.com/dh-hos/dhg.hospitalservices/commit/8574ad68ce76555d55946a4b2186272c31b1a143)
