### ISSUE TITLE
Yêu cầu - Bổ sung chức năng xuất xml tự động gửi lên cổng Sở y tế Đồng Tháp (87197 - cs2 bv Lấp Vò)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#29]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87197`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **CS2 BV Lấp Vò**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
CS2 BV Lấp Vò - mabv: 87197

Đề nghị bổ sung chức năng xuất xml tự động khi kết thúc đợt điều trị!

```

**Comment by ongtrieuhau** [comment]
Cập nhật 

- Admin [3.23.0412.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/fe934752c32b0c2df192a727baa1ccb93dfd0f25)
- Services [3.23.0412.1](https://github.com/dh-hos/dhg.hospitalservices/commit/5787b1d1f4f0b04c5806f5c5909a021354d5b485)

**Comment by le-an-87** [comment]
đã bổ sung!
