### ISSUE TITLE
Yêu cầu - Thực hiện Mô tả chi tiết cột 25 [MA_BAC_SI] khi xuất XML 4210.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#31]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Sản Nhi ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbsannhist`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện Admin và Services, khi xuất XML 4210, bảng 3 cột MA_BAC_SI vẫn chỉ lấy có mã của BS thực hiện(nếu có) hoặc mã của BS chỉ định, chứ chưa ghép mã BS chỉ định và BS thực hiện như mô tả https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/Vinh-Mo-ta-XML4210-XML3.MA_BAC_SI.md

Dữ liệu BN: Mã BN 2023019891, Mã KB 2303009194, ngày khám 24/03/2023, tháng KT 03, năm KT 2023.
Bn này có trả KQ siêu âm rồi.

Admin
![image](https://user-images.githubusercontent.com/99630883/232435704-ea56f68f-9e9d-4255-9d9c-0f51f04c79d3.png)

Report thì có đủ
![image](https://user-images.githubusercontent.com/99630883/233245595-b8d295ff-6e6d-4913-9c25-84e576a619b3.png)

**Comment by lqbinh1987** [comment]
Nhờ anh @ongtrieuhau xem lỗi này dùm.

**Comment by ongtrieuhau** [comment]
Cập nhật 
- Admin [3.23.0508.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/962126712ee6e405dc92faa9e5d0d018cd288842)
- Services [3.23.0508.1](https://github.com/dh-hos/dhg.hospitalservices/commit/8c35470c47e168c0f2287ff69d28d3ab9c6db0bc)
