### ISSUE TITLE
Yêu cầu - Thực hiện mô tả công văn 31/BHXH

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitaladmin#32]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

```
[chi_tiet_yeu_cau](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/20230415-Hau-CV1731-BHXH-G%C4%90%C4%90T-Thanh-toan-phau-thuat-vo-cam-gay-te.md)

```

**Comment by nghivanbi** [comment]
- @ongtrieuhau thực hiện tạo tham số và cấu trúc theo mô tả luôn nhé!

**Comment by ongtrieuhau** [comment]
Cập nhật Admin [3.23.0418.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/985d94348906ae648d92caa5c74da4b1a265abdf)

**Comment by nghivanbi** [comment]
@le-an-87 hỗ trợ test theo mô tả nhé

**Comment by le-an-87** [comment]
em không thấy file cài đặt anh @ongtrieuhau ơi!

**Comment by ongtrieuhau** [comment]
Check lại nhé @le-an-87 , do máy chủ bị tắt nên không có file cài đặt.

**Comment by le-an-87** [comment]
ok có rồi anh.

**Comment by le-an-87** [comment]
Em test thử 1 bệnh nhân thì chức năng xuất XML -> Xem xml 4210 vẫn chưa áp dụng đc theo mô tả nhe anh @ongtrieuhau 

Chỉnh tham số và cấu hình cls
![image](https://user-images.githubusercontent.com/96155021/232988125-f6f04f30-3605-43b6-a3b8-ef23d5d4f4bf.png)
Xem XML3 - chức năng kiểm tra xuất xml
![image](https://user-images.githubusercontent.com/96155021/232988334-7b51020f-6586-4144-92bc-4554fedb8401.png)
mô tả
![image](https://user-images.githubusercontent.com/96155021/232988394-2458ef50-4fc7-4dfa-9f78-224c781c8dfb.png)

**Comment by ongtrieuhau** [comment]
Cập nhật 
- Admin [3.23.0504.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/8ef4737631babe6f05de448cae4660f73644fb9c)
- Services [3.23.0504.1](https://github.com/dh-hos/dhg.hospitalservices/commit/99efa3aa50187448a2059d1bc9d8b00fe15d1109)

**Comment by le-an-87** [comment]
alo anh @ongtrieuhau ơi!
Admin XML3 bị sai rồi anh ơi!
ghép cls thì đúng rồi
nhưng mã VTYT và tên dịch vụ ở dòng VTYT bị sai đó anh
![image](https://user-images.githubusercontent.com/96155021/236370573-84529537-f169-4bf9-aa37-0dbb96edfe2f.png)
![image](https://user-images.githubusercontent.com/96155021/236370607-8459694f-51ff-4be4-8d67-4b0f2a335c9c.png)

**Comment by ongtrieuhau** [comment]
Cập nhật Admin [3.23.0505.2](https://github.com/dh-hos/dhg.hospitaladmin/commit/56cdcbdce62a18787c1d8e51a7a89bf0528daace) thử nhé, ok thì build luôn Services. Bản cập nhật này chỉ fix chỗ thiếu tên nhé, còn mã thuốc thì thấy có thêm chữ _GT rồi nhé

**Comment by le-an-87** [comment]
Hiện tại Reports đang làm như vầy
![image](https://user-images.githubusercontent.com/96155021/236372220-ff13bfb4-9299-4e64-b44b-27c194e5f861.png)
đối với các vtyt toa kèm theo thì có thêm mã dịch vụ và tên dịch vụ nữa anh ơi!
hướng dẫn xml 4210 cũng có hướng dẫn chổ mã dịch vụ đó anh
![image](https://user-images.githubusercontent.com/96155021/236372620-9e3749cb-ba37-47ec-a775-8bde3b69d9c1.png)

**Comment by le-an-87** [comment]
XML3 cột mã VTYT, tên vtyt và tên dịch vụ -> Môt tả không có ghép đối với VTYT ở XML3 anh ơi
![image](https://user-images.githubusercontent.com/96155021/236375660-08f4e6c1-26fa-48b2-88a1-7f94bbda9bd8.png)

XML2 trường tên VTYT cũng sai so với mô tả luôn nhe anh!
![image](https://user-images.githubusercontent.com/96155021/236375747-67db24d4-9d6f-4ebe-aa2e-0b6cdbacfea3.png)

**Comment by ongtrieuhau** [comment]
Cập nhật Admin [3.23.0505.3](https://github.com/dh-hos/dhg.hospitaladmin/commit/5151eed492894f20c1e348c14310de825724b1c4)

**Comment by le-an-87** [comment]
1. XML2 ghép thiếu mã GT cho thuốc toa VTYT kèm theo
![image](https://user-images.githubusercontent.com/96155021/236401778-25b51244-2dcd-4b42-bc4c-84f290ebc2d2.png)


2. XML3 hiện tại đúng rồi nhe anh
![image](https://user-images.githubusercontent.com/96155021/236401836-8b256c15-6e10-4dac-bb28-273139d29169.png)

**Comment by ongtrieuhau** [comment]
Cập nhật:
- Services [3.23.0505.1](https://github.com/dh-hos/dhg.hospitalservices/commit/0910079fe91165ab12100fc393c5c17d5feffae6)
- Admin [3.23.0505.4](https://github.com/dh-hos/dhg.hospitaladmin/commit/d9a6c2275b2934791c99b079a4f4a39ebe8cf413)

**Comment by le-an-87** [comment]
Đã cập nhật đúng theo mô tả!
