### ISSUE TITLE
Yêu cầu - Bổ sung DLL License

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitaladmin#33]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bổ sung hàm kiểm tra hạn key:
- Key còn hạn so với thời gian hệ thống --> true.
- Key hết hạn so với thời gian hệ thống --> false.

```

**Comment by ongtrieuhau** [comment]
Để thống nhất chức năng kiểm tra bản quyền giữa các module, thì sẽ không thực hiện theo hướng này, những mã khách hàng thuộc dạng này sẽ được add trực tiếp code, và tất cả module sẽ kiểm tra như hiện tại, không thay đổi.

**Comment by ongtrieuhau** [comment]
Cập nhật [License.dll;OTH.Adapter.dll](https://github.com/dh-hos/oLibraries/commit/bcd4a1ea940734ca460f976473c3f68b330bed73)
