### ISSUE TITLE
Yêu cầu - Tăng chiều dài cột dmmamay.mamay

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#35]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbthanhtri_form_mamay`

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Trước kia theo cấu trúc dmmamay.mamay là varchar(20), giờ theo nhu cầu của bv cần quản lý để người dùng chọn thì cần nhập luôn serial của máy vô cột mã máy, lơn hơn 20 ký tự, đã check Unlimited cho cột dmmamay.mamay, sau đó inport file excel vô thành công rồi, tắt form mở lại thì không được.
Kéo theo mấy module khác như: Pre, Labo, Diag khi mở form cấu hình máy lên lên thì báo lỗi ERROR: 22001: value too long for type character varying(20) - Hình 3, nguyên nhân là do trong dmmamay.mamay chưa giá trị >20 ký tự, nếu chỉnh <20 ký tự thì mở form danh mục mã máy ở admin và cấu hình máy mấy module lên được, nhưng khi đó cấu trúc dmmamay.mamay tự động set lại varchar(20).

Hình 1
![image](https://user-images.githubusercontent.com/99630883/233281807-34648360-6ccd-42ab-af8d-f5ab9e8c9dfe.png)

Hình 2
![image](https://user-images.githubusercontent.com/99630883/233281885-92b961c7-aa98-42d7-ab3d-afa552d60901.png)

Hình 3
![image](https://user-images.githubusercontent.com/99630883/233515061-6edb8f15-324c-49b5-a486-6584179ad974.png)

**Comment by nghivanbi** [comment]
@ongtrieuhau tạo cập nhật cấu trúc cập nhật cho tất cả nhé

**Comment by ongtrieuhau** [comment]
Cái này phải qui định là Yêu cầu mới thì mới đúng, do người dùng tự ý thay đổi cấu trúc dữ liệu, không thông qua Tổ lập trình, nên đâu phải lỗi.

**Comment by ongtrieuhau** [comment]
- Cập nhật Admin [3.23.0425.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/1110b5a09080e53598056461e32c4d15868b1c99)
- Các module khác có sử dụng Form Cấu hình máy cập nhật dll tại [oLibraries](https://github.com/dh-hos/oLibraries/commit/8e428741cf9683c3ec645b8a139fe02bfdde40b9) 

Ps: @nghivanbi , @vuongdh , @vinh-dh , @lequocthong29

**Comment by nghivanbi** [comment]
Cập nhật:
Register:[ v3.23.0426.1](http://www.fsend.vn/download/xha6RL-y3WXYWzSbIiT62RKkXeYi0bZL)
Prescription:[ v3.23.0426.1](http://www.fsend.vn/download/C6akZjx8WuhFZrMAAI7QBp54mSPIPhmK)

**Comment by vinh-dh** [comment]
- [HospitalDiagnoseSetup20230428](https://gofile.me/78TQg/YUWT9cOUl)
- [HospitalLaboratorySetup20230428](https://gofile.me/78TQg/sD3sg46he)
