### ISSUE TITLE
Yêu cầu - Đề nghị ghép mã Thuốc theo công văn 31/BHXH-GDBHYT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#36]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dean06_gcs_gbt_ksk`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Áp dụng công văn [31/BHXH-GDBHYT](https://github.com/dh-hos/Mo-ta-he-thong/issues/24)
```
Bệnh viện Phụ sản cần thơ đề nghị ghép mã thuốc theo công văn 31/BHXH-GDBHYT
Hiện tại phần mềm ghép cụm từ _GT vào sau mã thuốc -> MATHUOC_GT
Công văn hiện tại yêu cầu ghép mã dịch vụ & _GT vào sau mã thuốc -> MATHUOC_MADVKT_GT

```
![image](https://user-images.githubusercontent.com/96155021/237046736-2e230eff-a0f1-423b-8751-81d0b7825c79.png)

Công văn qui định
![image](https://user-images.githubusercontent.com/96155021/237046842-a5343326-0225-46cf-88df-dd0615613e9f.png)

**Comment by ongtrieuhau** [comment]
Cập nhật: 
- Admin [3.23.0515.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/4c8d3e23f6f8c8791d9872e2e0440afad5e349ba)
- Services [3.23.0515.1](https://github.com/dh-hos/dhg.hospitalservices/commit/1520672fe592774fdfb184f47c7235d8de66e363)

**Comment by le-an-87** [comment]
Đã cập nhật đúng theo mô tả! https://github.com/dh-hos/Mo-ta-he-thong/commit/5717ecc3c5544f52305e51d8cf6862b6db202dba
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/0b56fca0-40d0-4340-8882-50abaee8cf48)
