### ISSUE TITLE
Yêu cầu - Bổ sung tham số khi xuất XML3.MA_BAC_SI.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#39]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `70071`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Bình Long**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `bi_bvbinhlong_12052023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại phần mềm đã đáp ứng theo [mô tả](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/Vinh-Mo-ta-XML4210-XML3.MA_BAC_SI.md). Chổ XML3.MA_BAC_SI, đối với công khám và tiền giường thì thể hiện mã BS chỉ định thì ok, phần mềm đang đúng.
     Nhưng hiện tại những dịch vụ kỹ thuật có thực hiện thì một số BV đang bị xuất toán(cụ thể là TTYT Huyện Bình Long) vì lý do giám định viên cho rằng: 
**Đối với những dịch vụ kỹ thuật có thực hiện, chỉ thể hiện một hoặc nhiều mã bác sĩ thực hiện cách nhau bằng dấu Chấm phẩy (";")** 
Do phần này BH đang xuất toán tay, không phải cổng tự động, nên mỗi nhận viên giám định mỗi chổ hiểu khác nhau.

 Nên e đề nghị chổ XML3.MA_BAC_SI bổ sung tham số để BV lựa chọn, đối với những dịch vụ kỹ thuật có thực hiện:
          **1. Ghi tất mã bác sĩ chỉ định và tất cả mã bác sĩ thực hiện cách nhau bằng dấu Chấm phẩy (";")**
          **2. Chỉ ghi mã bác sỹ hoặc nhân viên y tế thực hiện dịch vụ, trường hợp nhiều nhân viên y tế cùng thực hiện dịch vụ kỹ thuật thì ghi mã bác sĩ cách nhau bằng dấu Chấm phẩy (";")**

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/99630883/eff9d3a0-e6ba-454a-83d6-4ae1e7726447)

**Comment by nghivanbi** [comment]
@ongtrieuhau phân công bổ sung mô tả để xử lý như yêu cầu nhé

**Comment by lqbinh1987** [comment]
Này nhiều BV đang bị xuất toán nhe anh @nghivanbi anh @ongtrieuhau

**Comment by nqhoa1005** [comment]
Bình Long đang cần gấp để gửi lại tháng 7, check chổ này dùm em gấp để hết hạn gửi lại nó sẽ xuất toán BV

**Comment by ongtrieuhau** [comment]
Anh @vinh-dh xem bổ sung thêm [mô tả](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/Vinh-Mo-ta-XML4210-XML3.MA_BAC_SI.md) theo yêu cầu nhé a

**Comment by vinh-dh** [comment]
[[Mô tả] Cách ghi nhận giá trị cột XML3.[MA_BAC_SI] (cột 25, bảng 3 - XML4210) - Cập nhật: 14/08/2023](https://github.com/dh-hos/Mo-ta-he-thong/commit/e4f427bb8db3a97d1ebffa3db9d8fc1108bd87e4)

**Comment by nghivanbi** [comment]
@ongtrieuhau xem có góp ý gì không để thực hiện hỗ trợ gấp các đơn vị nhé.

**Comment by lqbinh1987** [comment]
@ongtrieuhau anh xem coi chổ này dùm em để thực hiện cho BV, vì BH đang đợi BV gửi lại, trễ quá sẽ bị xuất toán.

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau , chổ này BV nó bị BH nhắc nhiều quá rồi anh
