### ISSUE TITLE
Yêu cầu - Cập nhật thêm Lisence 77156 [Hợp đồng thuê] - Hoàn thành 

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitaladmin#42]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77156`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Phòng Khám Đa Khoa Phúc Gia Khang**
- ![khach_hang](https://img.shields.io/badge/Hoàn%20thành-:-blue?style=plastic&logo=github) **06/06/2023**
###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
chi_tiet_yeu_cau
Mã BV: 77156
Tên: Phòng Khám Đa Khoa Phúc Gia Khang
Địa chỉ: Ấp Thạnh Sơn 2B, Xã Phước Tân, Huyện Xuyên Mộc, BR-VT
Điện thoại: 0254.389.1868

```

**Comment by ongtrieuhau** [comment]
Cập nhật dll [tại đây](https://github.com/dh-hos/oLibraries/commit/9586ffa5629de6c39bbf0c1ebe75e9f6dc1d0a12)

**Comment by nghivanbi** [comment]
@ongtrieuhau, @vinh-dh cập nhật DLL cho các module nhé

**Comment by chauthanhtra** [comment]
Cho em xin phần mềm mới có key để cập nhật cho PK nha anh @ongtrieuhau , @vinh-dh , @nghivanbi

**Comment by ongtrieuhau** [comment]
Cập nhật lại dll mới tại đây nhé anh @nghivanbi , @vinh-dh

**Comment by ongtrieuhau** [comment]
Cập nhật 

- Printer [3.23.0606.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/55c76bac0e49a093c723d3be549faaadbcdd7607)
- Admin [3.23.0606.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/d15c2810587d6c3432611caba2d96f25a4904ddb)
- Fees [3.23.0606.1](https://github.com/dh-hos/dhg.hospitalfees/commit/647f816c5f42a1b374bbe6dfcfe95d7a47cd2101)
- Services [3.23.0606.1](https://github.com/dh-hos/dhg.hospitalservices/commit/6dfb81746b0f23f96ff725bdc9a8a1043dfab027)

**Comment by nghivanbi** [comment]
Cập nhật:
Register:[ v3.23.0606.2](http://www.fsend.vn/download/dVf-uDtcipLIsieZs5q-teqlakdXm5z5)

**Comment by chauthanhtra** [comment]
Cho em xin phần mềm mới có key để cập nhật cho PK nha anh @vinh-dh

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230607](https://gofile.me/78TQg/dm8jtCT97)
- [HospitalDiagnoseSetup20230607](https://gofile.me/78TQg/1zcdpGxiI)
- [HospitalLaboratorySetup20230607](https://gofile.me/78TQg/eRfBZITdp)

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230608](https://gofile.me/78TQg/IOGs266Oy)
- [HospitalDiagnoseSetup20230608](https://gofile.me/78TQg/ZTpNP7jRu)
- [HospitalLaboratorySetup20230608](https://gofile.me/78TQg/MHIHWfqre)
