### ISSUE TITLE
Yêu cầu - Cập nhật thêm Lisence 77155 [Hợp đồng thuê]

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitaladmin#43]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77155`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA ĐỒNG TÂM**
- ![khach_hang](https://img.shields.io/badge/Hoàn%20thành-:-blue?style=plastic&logo=github) **21/06/2023**
###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
chi_tiet_yeu_cau

```

**Comment by ongtrieuhau** [comment]
Cập nhật: 

- Libraries: [Cập nhật Lisence 77155](https://github.com/dh-hos/oLibraries/commit/516762666bab611c806fc1df94804d82af2ee794)
- Admin: [3.23.0621.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/eb099412a6c1a7196440ceb2e72c980c8466f590)
- Printer: [3.23.0621.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/285d547a208ae127852e370407947ce80971fe05)
- Fees: [3.23.0621.1](https://github.com/dh-hos/dhg.hospitalfees/commit/9a7e5e7568019ade266f442f3bea2fcd97213cb4)

**Comment by nghivanbi** [comment]
Cập nhật:
- Register: [v3.23.0621.1](http://www.fsend.vn/download/_DO7aH0tYRAZpk5GdG48xsgfNHNIM8hN)

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230621](https://gofile.me/78TQg/yiZxdEyaM)
- [HospitalDiagnoseSetup20230621](https://gofile.me/78TQg/X9v7k15P1)
- [HospitalLaboratorySetup20230621](https://gofile.me/78TQg/mgpmziglP)
