### ISSUE TITLE
Lỗi - HS bệnh án ngoại trú gửi tự động nhiều lần trong ngày

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#44]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thốt nốt**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_full_29_06_2023`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2017900019` - _**MaKB**_: `2306015482` - _**MaBA**_: `N2017900019` _**NgayKCB**_: `28/06/2023` - _**MaPhong**_: `HIV` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
HS bệnh án ngoại trú ARV phần mềm gửi tự động hơn 2000 lần trên ngày

-> kiểm tra thấy mã liên kết không có gắn mã bv.

* Do dữ liệu full nặng và thêm data _overdata nên em không có úp lên nas nhe anh!
```
nhất ký đã gửi xml
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/b3bb8458-f6b6-44e8-a4ed-ce60a538111a)

Thông tin bệnh án
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/33c7284c-3a14-4517-a38b-f76882777fdc)

**Comment by ongtrieuhau** [comment]
Hiện tại đang lấy mabvkb trong psdangky để ghép mã trong ma_lk, nhưng dữ liệu bị thiếu nên mới gây lỗi. Chỗ này nhờ @nghivanbi kiểm tra lại chỗ này.
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/58720300/62d4c3c2-5e24-4b10-811a-4192b30947ef)
