### ISSUE TITLE
Lỗi - Dữ liệu đã gửi BHXH lỗi khi lấy dữ liệu

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitaladmin#46]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Giá Rai**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_giarai`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/YXAsLgjql

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2016029724` - _**MaKB**_: `2305014442` - _**MaBA**_: `2023006180` - _**NgayKCB**_: `02/06/2023` -_**ThangKT**_: `06` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Dữ liệu đã gửi BHXH: BN chẩn đoán tên bệnh có ký tự đặc biệt nên khi Lấy dữ liệu phần mềm không hiểu nên báo lỗi

```
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/98437757/0ef4fc67-500f-4a81-9563-7db5e864b2f1)

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/98437757/fc490589-53cb-491d-8484-be60f490fcd8)

**Comment by minhduc2it** [comment]
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/98437757/ad17a264-37bc-44e8-823a-1ee08f470cbf)

Bảng này xem vẫn còn lỗi

**Comment by le-an-87** [comment]
alo anh @ongtrieuhau ơi coi giùm em chổ này với nhe. để BV kiểm tra xem xml gửi cổng lấy dữ liệu thế nào nhe anh!
