### ISSUE TITLE
Lỗi - Liên thông Dược quốc gia số lượng thuốc lớn hơn kiểu dữ liệu Int16

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaladmin#47]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/8/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51214`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nội Tiết**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_noitiet_duocquocgia`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/EjUjhpDUj)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `P35` - _**SoHD**_: `00005593` - _**NgayHD**_: `9/8/2023` - _**ThangKT**_: `08` - _**NamKT**_: `2023`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Lỗi khi liên thông chứng từ Dược quốc gia 
Chứng từ nhập có thuốc có số lượng nhập là 36000 viên khi gửi dữ liệu phần mềm báo lỗi "Value was either too large or too small for an Int16" (số lượng thuốc vượt giới hạn kiểu dữ liệu Int16) 

![ảnh](https://github.com/dh-hos/dhg.hospitaladmin/assets/97272332/eff3ebbd-bebb-42f5-a2e7-66c98120b6ce)
![ảnh](https://github.com/dh-hos/dhg.hospitaladmin/assets/97272332/824bea6e-d6e4-43fb-ae6b-387d6ee279e2)

**Comment by ongtrieuhau** [comment]
Cập nhật 

-  Admin [3.23.0911.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/7bdd328cd696124c9aeed07bd3d912d35cae9023)
- Libraries: [99ab5d3](https://github.com/dh-hos/oLibraries/commit/99ab5d34650f1d8a37f0041a7e0be6995c6616ba) 
PS: nhờ anh @nghivanbi thực hiện cập nhật cho module Dược

**Comment by chauthanhtra** [comment]
Cập nhật Medicine mới giúp em nha anh @nghivanbi

**Comment by nghivanbi** [comment]
Cập nhật:
Medicine:  [3.23.0914.1](http://www.fsend.vn/download/KgTNlPtpoENsRMQjhvwbtLU1_KM_7oVR)
