### ISSUE TITLE
Lỗi - Hiệu chỉnh thông tin không cập nhật được tuyenxml.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#49]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/10/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_q12_t10`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023098634` - _**MaKB**_: `2310025931` - _**MaBA**_: `MaBA` _**NgayKCB**_: `23/10/2023` - _**MaPhong**_: `09` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại khi hiệu chỉnh thông tin bn ngoại trú ở modulde Admin thì phần mềm không cập nhật đúng psdangky.tuyenxml.
Như hình thì đa chỉnh BV cùng tuyến, lưu lại nhưng psdangky.tuyenxml vẫn là 1, ngược lại cũng vậy.
Reg và Pre chỉnh thì cập nhật đúng.
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/99630883/f6bb0294-3604-46a2-9a16-c733a8602b0e)

**Comment by ongtrieuhau** [comment]
@nghivanbi check loi nay nhe

**Comment by nghivanbi** [comment]
Cập nhật cho anh DLL: HosReg.Plus.dll thay cho Plus.dll nhé.

**Comment by ongtrieuhau** [comment]
Cập nhật [Admin 3.23.1029.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/e7f3fbbe61bb28766755e3adba9369d4af28f0f5)
## 
<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitaladmin/blob/main/Deploy_Tools/CHANGELOG.md)
</div>
