### ISSUE TITLE
Lỗi - XML3 không lấy được mã nhân viên thực hiện (BV Tâm Phúc)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#52]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamphuc_mabs`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/oLCCuUMPo)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022055552` - _**MaKB**_: `2311004749` - _**NgayKCB**_: `18/11/2023` - _**MaPhong**_: `KNO1` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2023`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `SI114`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng gửi tự động XML3 không load được mã bác sĩ thực hiện.

Hiện tại module admin có tham số tùy chỉnh lấy mã bs chỉ định hoặc lấy mã bs thực hiện. (đang lỗi không lấy được mã bs thực hiện)
Module Reports gôm tất cả mã bs chỉ định và bs thực hiện.

=> đề nghị điều chỉnh cho đồng bộ giữa 2 module.
-> do nhiều khách hàng hiểu khác nhau về QĐ 4210 nên đề xuất thêm tùy chỉnh để 2 module đồng bộ dữ liệu với nhau.

```
MaBS XML3 theo QĐ 4210
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/f1a41d4e-f7e4-47b4-b534-75a5d3709a3c)

Admin không load được mã bác sĩ thực hiện
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/0f87be28-3dbf-4541-8d57-c170a6dd24bc)

**Comment by le-an-87** [comment]
anh coi giùm em chổ này anh @ongtrieuhau ơi. bv hối, bị BH xuất toán anh ơi.

**Comment by ongtrieuhau-dh** [comment]
ok, để anh coi

**Comment by nghivanbi** [comment]
Cái này bổ sung thêm option lấy cả 2: bs chỉ định, bs thực hiện có các đơn vị chỉ động thực hiện @ongtrieuhau

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [Admin 3.24.0129.1](https://gofile.me/78TQg/O0PzOsHrX)
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/155862740/7ec10c48-c671-4e72-939a-eaa01692436d)

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [Services 3.24.0129.1](https://gofile.me/78TQg/Dvgyhdd7R)

**Comment by nghivanbi** [comment]
@le-an-87 coi này sớm để hỗ trợ các bv

**Comment by le-an-87** [comment]
Admin chổ tham số này em cấu hình loại nào cũng load tất cả mã bs luôn đó anh @ongtrieuhau ơi
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/f730e927-1017-410f-88ef-e4fbb4b261cd)
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/8440e77d-bbf8-44a5-87f3-4f4260753a04)

**Comment by le-an-87** [comment]
Dữ liệu test: an_phusan_tonkho_tutruc_22122023
NgayKCB: 30/01/2024

**Comment by ongtrieuhau-dh** [comment]
Chỉnh option này phải tắt mở lại á, nếu tắt mở lại vẫn lỗi thì cho hay nhé

**Comment by le-an-87** [comment]
chỉnh là tắt mở lại hết anh ơi

**Comment by ongtrieuhau-dh** [comment]
Những nhân viên này thuộc ekippt nên lấy lên hết nhé, cái option này đang áp dụng đối với những cận lâm sàng có thực hiện xml4

**Comment by le-an-87** [comment]
chổ option đó admin diễn giải là áp dụng xml3 mà anh
nếu không áp dụng cho xml 3 thì chổ đó anh sửa lại luôn nhe
còn xml 4 là cho chi số kết quả cls
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/881fe245-61a0-4f95-9cc8-88d2f606f893)

**Comment by le-an-87** [comment]
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/59f02278-e41b-42e9-8266-37d7936c8c22)
chổ này không áp dụng cho cls nào anh diễn giải rõ hơn để người dùng biết đường sử dụng nhe anh.

trường hợp các cls không áp dụng ở option này là lấy hết tất cả mã bs đúng không anh

**Comment by ongtrieuhau** [comment]
Uh. Lấy theo ê kíp phẫu thuật nhé.

**Comment by le-an-87** [comment]
1. Đề nghị chỉnh sửa lại diễn giải option rõ hơn để người dùng hiểu và áp dụng nhe anh
-> Mã bác sĩ (MA_BAC_SI, NGAY_KQ) trong xml3
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/0675b08f-da30-4d00-9d2f-c1282032e2a7)

2. trường hợp cấu hình option Lấy theo thông tin ghi nhận kết quả, nếu không có kết quả sẽ lấy theo thông tin chỉ định
-> Admin chưa lấy đúng theo diễn giải hiện tại chỉ lấy mã bs chỉ định
=> cụ thể cls SO19: soi cổ tử cung / không lấy bs thực hiện 242 mà lấy bs chỉ định tài khoản admin 000
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/4d67a047-fe82-43f9-b0c1-204002e111af)

Reports có lấy mã bs thực hiện
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/fe20f197-951e-42ff-a2bc-ef195fc8956b)

**Comment by le-an-87** [comment]
3. Trường hợp cấu hình lấy thông tin chỉ định và ghi nhận kết quả
-> vẫn chưa lấy được mã bs thực hiện đối với cls không thuộc TTPT
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/7bffda2e-a369-4a70-a0eb-9f8b490bb496)
report
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/97ade5cc-5e67-4b2e-9375-d5d20e9a3cd8)

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupHospitalAdmin.v3.24.0131.1.msi](https://gofile.me/78TQg/m8aED1EUX)
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/155862740/3f7dd77e-6e73-42ba-b6d2-a39fb03090fb)

**Comment by le-an-87** [comment]
Chổ xét nghiệm chưa lấy được mã bs thực hiện nhe anh
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/5b8dfeb7-cfb9-49c5-a2c1-4dd6c8d4691e)
Đã trả kết quả
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/f0bceb19-41b3-4ccc-97f3-36f8b235d59b)
Reports
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/142a7fd6-6452-44a4-a2c2-acf86a2bd3bd)

**Comment by ongtrieuhau** [comment]
Xem xét nghiệm đó có trả kết quả hông nha?

**Comment by le-an-87** [comment]
em có gửi hình ảnh kết quả xét nghiệm kèm theo đó anh. anh cần thông tin gì thêm để chứng minh có kết quả?

**Comment by ongtrieuhau-dh** [comment]
Hiện tại xml4 đang loại bỏ những cái nào gia_tri trống, xem như chưa có ghi nhận kết quả, nên những cái này hông lấy lên xml4, nên xml3 sẽ lấy theo chỉ định.
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/155862740/35240ab2-1cca-4a16-99b1-68c0817553e7)

**Comment by le-an-87** [comment]
anh nói những cái không lấy theo xml4 là lấy hết các mã bs mà.
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/eb79be0d-51ad-454e-b506-07916e664586)

**Comment by le-an-87** [comment]
XMl4 là bảng chỉ số xét nghiệm. những cái không có chỉ số thì đâu load lên đó.
Trường hợp này anh xem giải quyết giùm em luôn nhe.
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/9b8c4873-2afc-4c90-a3b5-fb585a62cf6b)

**Comment by ongtrieuhau-dh** [comment]
Theo công văn thì những người có tham gia vô thực hiện cls thì lấy lên, cái này hổng có kết quả, thì xem như chưa thực hiện, nên hiện tại hổng có lấy lên. Option cũng nói rõ là lấy theo XML4, cái này xml4 hổng có, thì đâu có theo được.

**Comment by le-an-87** [comment]
anh nói vậy sao thủ thuật có.

**Comment by ongtrieuhau-dh** [comment]
Thủ thuật là bảng 5, hiện đang theo công văn đó
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/155862740/dd8de5eb-f596-40e5-957c-f6911c0fdfda)

**Comment by le-an-87** [comment]
Hiện tại chổ này BV đang báo cls gửi tự động không lấy được mã bác sĩ thực hiện ở XML3. trường hợp option của anh áp dụng cho các cls của xml4 thì em không kiểm tra option của anh nữa.
nhưng xml3 Admin chưa load được mã bs của các cls này. Reports thì load được.
các cls này anh nói không có kết quả thì nhờ anh @vinh-dh vào kiểm tra giùm em trường hợp này cái nhe. xác định xem có kết quả hay không? nếu không có thì Reports chỉnh lại giống admin giùm em.

**Comment by le-an-87** [comment]
Thống kê xuất XML có mã bs thực hiện
-> khi gửi thì không có mã bs thực hiện.
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/39949d7f-2106-4fa9-a68b-d7b84ac4b546)
Dữ liệu đã gửi
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/9bd0cdaf-fd9a-41a0-888e-380cbf0e19da)

anh coi giùm trường hợp này nhe.
dữ liệu: an_tamphuc_mabs_cdha_xml3_02022024.
link tải dữ liệu: https://gofile.me/78TQg/wpyV1mS6q
Mã BN: 2024004337
makb: 2402000350
macls: SI114

**Comment by nghivanbi** [comment]
này @vinh-dh cập nhật mô tả này: 
https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/Vinh-Mo-ta-XML4210-XML3.MA_BAC_SI.md
Thống nhất xác định cls có kết quả, đảm bảo các module lấy giống nhau nhé.

**Comment by vinh-dh** [comment]
Theo mô tả đó thì XN lấy lên hết (không quan tâm tới cột ketqua ở table psmotaxn có rỗng hay không) rồi đó.

**Comment by nghivanbi** [comment]
HA thì sao?

**Comment by vinh-dh** [comment]
Coi chi tiết của mô tả đó:
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/112069710/d4208a05-5183-4639-a5d0-8e738d17a405)

**Comment by nghivanbi** [comment]
@ongtrieuhau thực hiện theo mô tả nhé.

**Comment by le-an-87** [comment]
Đã fix theo git https://github.com/dh-hos/To_Lap_Trinh/issues/240
