### ISSUE TITLE
Lỗi - Kết chuyển dữ liệu đã xóa

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitaladmin#57]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Quân Dân Y Sóc Trăng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_qdyst_full_catdata`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/pQl5gdAuq

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**ThangKT**_: `01` - _**NamKT**_: `2018`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
mo_ta_loi

```
Kết chuyển dữ liệu đã xóa:
Tháng 01 năm 2018 dữ liệu kết chuyển chỉ qua 1 được phần và báo lỗi
(Các tháng khác trong 2018 kết chuyển bình thường)

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/98437757/89c0c159-005c-4eee-9b4c-e41c29ed2bb9)

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/98437757/63abf444-30ba-44f1-b5e8-9a49b66f9c69)

File chi tiết lỗi  [Chi tiet loi.txt](https://github.com/dh-hos/dhg.hospitaladmin/files/14401619/Chi.tiet.loi.txt)

**Comment by ongtrieuhau-dh** [comment]
Hỗ trợ bệnh viện chạy script này nhé 

`ALTER TABLE recycle.pshdxn ALTER COLUMN stt TYPE NUMERIC(6,0);`

**Comment by minhduc2it** [comment]
Đã hỗ trợ chạy script thành công
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/98437757/08462358-26ef-4f85-9879-a90282478bae)
