### ISSUE TITLE
Lỗi - Cập nhật cấu trúc XML 130 (Script 1) (BV Châu Thành ĐT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#62]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Châu Thành ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_chauthanh_dt_21042024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_chauthanh_dt_21042024`](https://gofile.me/78TQg/aaSVlwH15)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `(Script 1) Cấu trúc hỗ trợ XML 130`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Cập nhật cấu trúc XML 130 (Script 1) báo lỗi.

BV sử dụng postgres 9.3
Dữ liệu kiểm tra với postgres 11. không bị lỗi

```
![ảnh](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/f5373d2b-4f98-4ce2-8f51-208fb2b00431)
![ảnh](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/0cd3d6e4-2ea7-491e-88ff-65b363e0fd09)
![ảnh](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/7237184e-48f7-4cad-bab8-01e24fe90be2)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitaladmin/62)

**Comment by vinh-dh** [comment]
Chạy riêng [script1 (1).txt](https://github.com/dh-hos/dhg.hospitaladmin/files/15056457/script1.1.txt) này cho đơn vị nào gặp lỗi này nhé! Nguyên nhân: BV đang sử dụng PostgreSQL phiên bản cũ, nên cấu trúc mới không hỗ trợ.

**Comment by ongtrieuhau-dh** [comment]
@vinh-dh viết lại script mới để có thể chạy được trên cả bản cũ và bản mới luôn nhé, để sau này có thể up trên admin luôn, thống nhất 1 script duy nhất

**Comment by vinh-dh** [comment]
Script trước đã có, BV đã chạy. Viết lại đưa lên là các BV đã chạy trước đó sẽ bị lỗi.

**Comment by ongtrieuhau-dh** [comment]
Thì anh @vinh-dh viết thế nào để 1 script có thể chạy hết, hông phân biệt phiên bản postgres, hoặc kiểm tra phiên bản để thực thi script, chứ như vầy sao đưa lên admin được. Anh xem viết lại để thống nhất 1 script nhé

**Comment by vinh-dh** [comment]
Chỉ 1 số ít BV còn sử dụng bản cũ. BV nào bị thì chịu khó chạy riêng trước đi.

**Comment by le-an-87** [comment]
Đã hỗ trợ chạy trực tiếp tại TTYT Châu Thành ĐT

> Chạy riêng [script1 (1).txt](https://github.com/dh-hos/dhg.hospitaladmin/files/15056457/script1.1.txt) này cho đơn vị nào gặp lỗi này nhé! Nguyên nhân: BV đang sử dụng PostgreSQL phiên bản cũ, nên cấu trúc mới không hỗ trợ.
