### ISSUE TITLE
Lỗi -  cập nhật cấu trúc hỗ trợ tạo index table ttcon (BV Châu Thành ĐT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaladmin#63]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Châu Thành ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_chauthanh_dt_21042024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_chauthanh_dt_21042024`](https://gofile.me/78TQg/aaSVlwH15)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: ` cấu trúc hỗ trợ tạo index table ttcon`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Cập nhật cấu trúc hỗ trợ tạo index table ttcon báo lỗi.

BV sử dụng postgres 9.3
Dữ liệu kiểm tra với postgres 11. không bị lỗi

```
![ảnh](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/f5373d2b-4f98-4ce2-8f51-208fb2b00431)
![ảnh](https://github.com/dh-hos/dhg.hospitaladmin/assets/96155021/7237184e-48f7-4cad-bab8-01e24fe90be2)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitaladmin/63)

**Comment by vuongdh** [comment]
@vinh-dh xem hỗ trợ cấu trúc chổ script 130 dùm hén

**Comment by vinh-dh** [comment]
Lỗi [script 1](https://github.com/dh-hos/dhg.hospitaladmin/issues/62) thì xem ở đây. Còn lỗi này @le-an-87 báo hình như là cái cấu trúc ttcon bên dưới thì phải.

**Comment by vuongdh** [comment]
@le-an-87 lỗi khi chạy index trên postgres cũ (9.3)(em có thể bỏ qua hoặc chạy bằng tay)

**Comment by vuongdh** [comment]
CREATE INDEX IF NOT EXISTS ttcon_idx ON current.ttcon
  USING btree (mabame, maba)
  WHERE (xoa = 0);
  
CREATE INDEX ttcon_idx1 ON current.ttcon
  USING btree (maba);
  
REINDEX TABLE current.ttcon;

**Comment by le-an-87** [comment]
> CREATE INDEX IF NOT EXISTS ttcon_idx ON current.ttcon USING btree (mabame, maba) WHERE (xoa = 0);
> 
> CREATE INDEX ttcon_idx1 ON current.ttcon USING btree (maba);
> 
> REINDEX TABLE current.ttcon;

Script này chạy báo lỗi em mới ghi nhận lỗi đó anh.

**Comment by vuongdh** [comment]
lỗi trên postgres cũ (script này cũ lắm rồi, anh không nhớ của ai đưa), anh đã xóa script rồi. Khi nào module nào cần thì sẽ hỗ trợ sau
