### ISSUE TITLE
Lỗi - Cập nhật cấu trúc bị lỗi.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#66]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1jMl1iVjxjtRThQ7U8JdKyWKY4tYUaG-U/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `ALL` - _**MaKB**_: `ALL` - _**MaBA**_: `ALL` _**NgayKCB**_: `ALL` - _**MaPhong**_: `ALL` - _**MaDV**_: `ALL` - _**ThangKT**_: `ALL` - _**NamKT**_: `ALL`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Cập nhật đến cấu trúc [script 6] Cấu trúc hỗ trợ XML 130 - Bổ sung QĐ 4750 (1) thì lỗi như sau:
[[script 6] Cấu trúc hỗ trợ XML 130 - Bổ sung QĐ 4750 (1).txt](https://github.com/user-attachments/files/15753072/script.6.C.u.truc.h.tr.XML.130.-.B.sung.QD.4750.1.txt)

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/99630883/0becf419-9192-4968-a83f-7658cf85999c)

Cập nhật ở BV thì lỗi script [script 7] Cấu trúc hỗ trợ XML 130 - Bổ sung QĐ 4750 (2): chạy ở bv thì bị mà lấy dl về máy thì không bị.
[[script 7] Cấu trúc hỗ trợ XML 130 - Bổ sung QĐ 4750 (2).txt](https://github.com/user-attachments/files/15753076/script.7.C.u.truc.h.tr.XML.130.-.B.sung.QD.4750.2.txt)

**Comment by vinh-dh** [comment]
OK, để anh kiểm tra. Gửi tên database nào chạy bị lỗi @lqbinh1987 ?

**Comment by vinh-dh** [comment]
Anh mới làm lại script. Nói BV thử lại nhé @lqbinh1987.

**Comment by lqbinh1987** [comment]
Vẫn còn 1 cấu trúc bị lỗi anh @ongtrieuhau .
Tên data: `binh_thotnot_hiv_bhyt`
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/99630883/a4352015-1105-4b55-8806-0fbe2374dee9)

**Comment by vinh-dh** [comment]
Thử lại lần nữa nhé @lqbinh1987.

**Comment by lqbinh1987** [comment]
Đã fix:
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/99630883/677f8a94-7100-4949-9f72-919635a0412d)
