### ISSUE TITLE
Lỗi - Cập nhật [script 6] Cấu trúc hỗ trợ XML 130 - Bổ sung QĐ 4750 (1) báo lỗi 

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitaladmin#68]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bv Đặng Thùy Trâm**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_dangthuytram_script6`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/pvuzzaHEM

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   >  _**ThangKT**_: `06` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Admin Cập nhật [script 6] Cấu trúc hỗ trợ XML 130 - Bổ sung QĐ 4750 (1) báo lỗi như hình bên dưới:
Bệnh viện đang chạy Postgres 9.4
[File chi tiết lỗi script 6.txt](https://github.com/user-attachments/files/15812914/File.chi.ti.t.l.i.script.6.txt)
Ghi chú: Dữ liệu lấy về chạy trên Server công ty Postgres 11. bình thường

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/98437757/782300ba-cf61-448a-9736-6fb72d3e7834)

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/98437757/e7a3fd8a-953e-472e-b18f-4888d5f645f0)

**Comment by vinh-dh** [comment]
Nói bệnh viện thử lại nhé @minhduc2it 
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/112069710/763b6b54-bf1a-4155-878a-218d1b9f135c)

**Comment by minhduc2it** [comment]
Anh @vinh-dh 
2 Script sau chạy báo lỗi:
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/98437757/9cf05b21-fb42-4aea-8c0b-e2eaef31fa36)

- BV Chạy Script 6 vẫn còn lỗi [File chi tiết lỗi script 6.txt](https://github.com/user-attachments/files/15814818/File.chi.ti.t.l.i.script.6.txt)

- Script 12 báo lỗi [File chi tiết lỗi script 12.txt](https://github.com/user-attachments/files/15814849/File.chi.ti.t.l.i.script.12.txt)

**Comment by vinh-dh** [comment]
Thử lại lần nữa nhé @minhduc2it 

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/112069710/1e653385-3387-48d1-ab4f-23e913a5ca5b)

**Comment by minhduc2it** [comment]
Bệnh viện báo đã cập nhật Script thành công 
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/98437757/a9a9c62f-b083-4ddd-8b45-6529a501a9da)
