### ISSUE TITLE
Lỗi - XML 3 chưa lấy được mã giường và mã người thực hiện cls

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitaladmin#69]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87044`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quân Dân Y Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquandany_magiuong`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/vEQExO9fh)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2406013457` - _**MaBA**_: `2024004344` _**NgayKCB**_: `29/06/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `05` - _**ThangKT**_: `06` - _**NamKT**_: `2024`

   > _**MaCLS**_: `GI10` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
 
Hiện tại XML3 :
Trường dữ liệu (32) cột MA_GIUONG chưa lấy được mã giường
Trường dữ liệu (34 ) cột NGUOI_THUC_HIEN chưa lấy được mã người thực hiện cls
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/97272364/80e094bc-08c3-4908-aed7-c11b6aa0990a)

**Comment by ongtrieuhau** [comment]
Ok

**Comment by vinh-dh** [comment]
Cập nhật mô tả [xml130.bang3: Chỉ tiêu chi tiết dịch vụ kỹ thuật và vật tư y tế](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang03%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md).
- Hướng dẫn điều kiện  cho cột `ngay_th_yl`.
- Hướng dẫn điều kiện  cho cột `nguoi_thuc_hien`.
- Bổ sung điều kiện bắt buộc cho cột `ngay_th_yl`.

**Comment by ongtrieuhau-dh** [comment]
@hvtuan1987 ma_giuong đã cập nhật trong bản mới nhất rồi nhé, còn nguoi_thuc_hien cũng đã lấy thông tin, nhưng dữ liệu chưa  nhập ekkippt nên lấy hông lên nhé

**Comment by ongtrieuhau-dh** [comment]
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/155862740/356fe764-1949-4a13-97e9-a62af968af1f)
