### ISSUE TITLE
Lỗi - Lỗi - Thông tin khám ARV chưa lên XML

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#70]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbbvdkomon_loan_2`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/VvkMqBco1)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018014235` - _**MaKB**_: `2407002276` - _**MaBA**_: `MaBA` _**NgayKCB**_: `02/07/2024` - _**MaPhong**_: `PL` - _**MaDV**_: `008` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Áp cho tất cả các BV chạy HIV.

- [ ] LOAI_DTRI_LAO - Vẫn còn lấy giá trị từ bảng fhi_gdxutri.malydo liên kết fhi_dmchon.loai=16(gửi cột 4750).

Chưa lấy được trường dữ liệu như đã chốt: Lấy dữ liệu fhi_dgxutri.maxutri liên kết fhi_dmxutri.maxutri, gửi khi fhi_dgxutri.maxutri = 2 hoặc 3 hoặc **10**(mới bổ sung 10 để cho đúng với danh mục của 130).
Như hình dươi đây có mã xử trí 2 và 3 (liên quan đến lao), nhưng không liên kết qua fhi_dmxutri.maxutri để gửi cột ma4750, mà vẫn còn lấy giá trị Mã lý do để liên kết bảng fhi_dmchon mà gửi cột 4750
![image](https://github.com/dh-hos/92010-send4750/assets/99630883/1bb382d9-4c52-4a06-aa30-96f38c90bfa4)
![image](https://github.com/dh-hos/92010-send4750/assets/99630883/1ec615d0-688b-46da-960d-44c1ef12357f)
![image](https://github.com/dh-hos/92010-send4750/assets/99630883/d4e46d8f-1124-4e0a-aa37-54ad41bfb77b)

- [ ] NGAY_TAI_KHAM - Lấy tại psdangky,ngaytaikham, dl có nhưng chưa lấy lên được.
![image](https://github.com/dh-hos/92010-send4750/assets/99630883/f33587a5-7098-4cd7-94b1-262da0105e33)

- [ ] MA_BENH_KT - Lấy tại fhi_qtdieutri.maicdp.
![image](https://github.com/dh-hos/92010-send4750/assets/99630883/52da977f-1ce2-491f-a36f-14be97d3f63f)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ❌ **Từ chối tiếp nhận** 
- 📣 **Nguyên nhân**: _Sai trạng thái "Gấp" (Gấp: là phần mềm không hoặc động được nữa.)_


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.] Nghĩa vụ: ghi nhận vi phạm nếu có tại HD.04, phản hồi
đủ thông tin

**Comment by ongtrieuhau-dh** [comment]
1. LOAI_DTRI_LAO => Code check lỗi
2. NGAY_TAI_KHAM => XML06 hiện chưa có nhé, lập yêu cầu mới 
3. MA_BENH_KT => XML06 hiện tại chưa có, đề nghịp lập yêu cầu mới

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @ongtrieuhau
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-05**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lqbinh1987** [comment]
Đề nghị hoàn thành 04/07 để TK hoàn thành việc đối chiếu số liệu online với Anh Dũng chốt 05/07

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0703.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407031-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407031-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407031-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: XML06.LOAI_DTRI_LAO (lấy maxutri để link dmchon lấy giá trị 4750)

- ![](https://i.imgur.com/rj6jaP3.png)

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/70

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
Cập nhật Git gửi dữ liệu 
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/155862740/0fa00a67-2d1c-49f2-82bc-646b0905e8f5)

**Comment by lqbinh1987** [comment]
Lấy sai chổ của ý e nói rồi anh @ongtrieuhau, ý e ở trên là **Chưa lấy được trường dữ liệu như đã chốt: Lấy dữ liệu fhi_dgxutri.maxutri liên kết fhi_dmxutri.maxutri, gửi khi fhi_dgxutri.maxutri = 2 hoặc 3 hoặc 10(mới bổ sung 10 để cho đúng với danh mục của 130).**
Nhưng hiện tại bản fix của anh lấy fhi_dgxutri.maxutri liên kết qua bảng fhi_dmchon

Ví dụ như BN có Mã xử trí là 2, thì map qua bảng fhi_dmxutri để gửi ma3750
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/99630883/6b5357f7-4145-4423-ab4b-5687034a30d0)

**Comment by ongtrieuhau-dh** [comment]
Thì đang lấy maxutri trong fhi_dgxutri để join qua dmchon loại 16, lấy 4750

**Comment by lqbinh1987** [comment]
**Lấy fhi_dgxutri.maxutri join qua bảng fhi_dmxutri để lấy giá trị cột ma4750 để gửi á anh.**
Không còn lấy fhi_dmchon nữa.

**Comment by ongtrieuhau-dh** [comment]
Vậy nói đơn giản vậy đi, cái này đúng ra phải là yêu cầu á, vì lúc trước yêu cầu như thế, lấy như thế, lại nói là lỗi, mấy chỗ này, do chưa biết cụ thể, anh đề nghị là yêu cầu mới hết, để làm theo cái mới thôi, do mình chưa hiểu rõ dữ liệu của nó thế nào

**Comment by lqbinh1987** [comment]
Đúng rồi anh.

**Comment by ongtrieuhau-dh** [comment]
Với kinh nghiệm, cụ thể dữ liệu của bệnh nhân, nêu mô tả cần lấy thôi, và cái giá trị mong muốn như thế nào, thì code sẽ dễ hình dung và lấy giá trị, cũng có cơ sơ để biết đúng sai theo cái yêu cầu nữa

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0703.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407033-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407033-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407033-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: XML06.LOAI_DTRI_LAO: Lấy fhi_dgxutri.maxutri join qua bảng fhi_dmxutri để lấy giá trị cột ma4750 để gửi.

- ![](https://i.imgur.com/Np7bfnQ.png) ![](https://i.imgur.com/bHw9r5M.png)

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/70

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/70#issuecomment-2206058751

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0703.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407033-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407033-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407033-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: XML06.LOAI_DTRI_LAO: Lấy fhi_dgxutri.maxutri join qua bảng fhi_dmxutri để lấy giá trị cột ma4750 để gửi.

- ![](https://i.imgur.com/Np7bfnQ.png) ![](https://i.imgur.com/bHw9r5M.png)

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/70

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/70#issuecomment-2206058751

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
**Cập nhật Git gửi dữ liệu** :

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/155862740/7ff5a71f-115f-41b5-acfb-44b59a6bc6ed)

**Comment by lqbinh1987** [comment]
Đã hỗ trợ
Admin
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/99630883/bf611e23-1964-4fe1-a9bd-4701969a9a24)

Git -> Medigate
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/99630883/6b8fe0e3-c515-4e48-a539-213d2c233039)
