### ISSUE TITLE
Lỗi -  PHÁT SINH LỖI THIẾU CỘT MAMAY KHI GỬI XML 4750

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitaladmin#73]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87163`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV TÂM THẦN ĐỒNG THÁP**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_bvttdt2024001274_xn_mamay`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/VZst4lcGK)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022004711` - _**MaKB**_: `2406004736` - _**MaBA**_: `2024001274` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phát sinh lỗi thiếu cột psmotaxn.mamay khi gửi XML 4750

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/130281806/9a479829-3695-42a4-b6f6-e23a9d2be19e)

đã chạy hết cấu trúc
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/130281806/e1d67d5d-15fd-4384-9336-1aee69467f98)
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/130281806/9e831ddc-b28c-49b8-83f5-cbb746ebcded)

em đã gửi thử Admin bản 04/07 thì không báo lỗi như trên và sau khi thông báo lỗi thì thông báo gửi thành công

chi tiết lỗi :  
[xn.mamay.txt](https://github.com/user-attachments/files/16122735/xn.mamay.txt)

**Comment by ongtrieuhau-dh** [comment]
👉 **Chạy cập nhật cấu trúc để fix**

![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/155862740/074f35d2-68f3-433c-8b61-15e9999c073b)

**Comment by nqhoa1005** [comment]
Đã fix
![image](https://github.com/dh-hos/dhg.hospitaladmin/assets/130281806/07eeacb0-c2e7-4c42-83b3-76103c93aa4f)
