### ISSUE TITLE
Lỗi - Xem XML của BN nội trú bị lỗi.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#76]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_q12_072024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/kPUDWSUvi)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023013555` - _**MaKB**_: `2407010129` - _**MaBA**_: `2024013329` _**NgayKCB**_: `09/07/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `19` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi click Xem 3750 của BN nội trú thì xuất hiện lỗi như hình dưới, BN nội trú nào cũng bị:
![image](https://github.com/user-attachments/assets/375ed60a-c303-445c-9d2f-bad6283bc027)

Error [0]Message: Lỗi code [XmlToDataTable].
<CHI_TIEU_DU_LIEU_TOM_TAT_HO_SO_BENH_AN>  <MA_LK>79029_2024_07_2023013555_2407010129_2024013329</MA_LK>  <MA_LOAI_KCB>09</MA_LOAI_KCB>  <HO_TEN_CHA />  <HO_TEN_ME>Trần Thị Vân</HO_TEN_ME>  <NGUOI_GIAM_HO>Trần Thị Vân</NGUOI_GIAM_HO>  <DON_VI />  <NGAY_VAO>202407082240</NGAY_VAO>  <NGAY_RA>202407090035</NGAY_RA>  <CHAN_DOAN_VAO>Nhiễm trùng đường ruột do vi khuẩn khác</CHAN_DOAN_VAO>  <CHAN_DOAN_RV>Viêm dạ dày - ruột và viêm đại tràng khác không rõ nguyên nhân</CHAN_DOAN_RV>  <QT_BENHLY>LDNV: nôn ói + tiêu lỏng
Tối ngày nhập viện, BN nôn ói 5-6 lần, tiêu lỏng
Tiền căn: chưa ghi nhận
Tỉnh, da niêm hồng
Chi ấm, mạch rõ, CRT <2S
Tim đều 
Phổi trong 
Bụng mềm, ân đau quanh rốn
Không dấu thần kinh khu trú
</QT_BENHLY>  <TOMTAT_KQ />  <PP_DIEUTRI>Nội khoa</PP_DIEUTRI>  <NGAY_SINHCON />  <NGAY_CONCHET />  <SO_CONCHET />  <KET_QUA_DTRI>2</KET_QUA_DTRI>  <GHI_CHU />  <MA_TTDV>0203314305</MA_TTDV>  <NGAY_CT>20240709</NGAY_CT>  <MA_THE_TAM />  <DU_PHONG /></CHI_TIEU_DU_LIEU_TOM_TAT_HO_SO_BENH_AN>

Error [0]HResult: -2146233088
Error [0]Source: OTH.Common
Error [0]StackTrace:    at OTH.Common.ClsExtensionMethods.XmlToDataSet(String xml)
   at OTH.XForms.HosAdmin.Reports.XFrmBKXuatXML4750.xmlToPage(XtraTabPage page, String xml)
   at OTH.XForms.HosAdmin.Reports.XFrmBKXuatXML4750.xml_TONGHOPMemoEdit_EditValueChanged(Object sender, EventArgs e)
Error [0]TargetSite: System.Data.DataSet XmlToDataSet(System.String)

Error [1]=== INNER EXCEPTION ===
Error [1]Message: Name cannot begin with the '2' character, hexadecimal value 0x32. Line 5, position 23.
Error [1]HResult: -2146232000
Error [1]Source: System.Xml
Error [1]StackTrace:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.ReadCurrentNode(XmlDocument doc, XmlReader reader)
   at System.Xml.XmlDocument.ReadNode(XmlReader reader)
   at System.Data.DataSet.ReadXml(XmlReader reader, Boolean denyResolving)
   at OTH.Common.ClsExtensionMethods.XmlToDataSet(String xml)
Error [1]TargetSite: Void Throw(System.Exception)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-15**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ❌ **Từ chối tiếp nhận** 
- 📣 **Nguyên nhân**: Chưa sử dụng bản mới nhất để kiểm thử 
![image](https://github.com/user-attachments/assets/134321a6-cab7-4838-b622-92fa0c331121)



[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.] Nghĩa vụ: ghi nhận vi phạm nếu có tại HD.04, phản hồi
đủ thông tin

**Comment by lqbinh1987** [comment]
Hiện em thử bản mới đã ok, do thời điểm đó em thử ở BV từ bản mới nhất cũng bị, đem về công ty em cũng thử tới lui đủ các bản mới cũng bị nên quên chạy lạ bản mới nhất tại thời điểm đó để báo.
![image](https://github.com/user-attachments/assets/f8348987-5981-42c0-92d6-76397d9ebc1c)
