### ISSUE TITLE
Lỗi - Không lấy được chẩn đoán vào XML1

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitaladmin#77]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `All`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbsangnhist_chandoanvao`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/DrxL7ScWb)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019053476` - _**MaKB**_: `2407000636` - _**MaBA**_: `MaBA` _**02/07/2024**_: `NgayKCB` - _**MaPhong**_: `PK034` - _**MaDV**_: `KS028` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

Bệnh nhân đầu tiên cho vô phòng PK016. Bs không khám và chuyển sang phòng khám PK034 bác sĩ chỉ định thuốc và cls..In bảng kê thì lúc này Admin lấy chẩn đoán vào từ phòng ban đầu (PK016 do phòng này không có chẩn đoán nên không lấy được).
Hình tại bảng khambenh
![image](https://github.com/user-attachments/assets/66df8ce2-7807-4b58-9cde-4e91114ae903)
Hình chuyển phòng
![image](https://github.com/user-attachments/assets/69cf64a6-bb2d-4fb9-9c28-16e4ce2e8290)
Hình tại form Xem XML4750
![image](https://github.com/user-attachments/assets/47b20da1-0e37-4799-bd68-2ba766b853ea)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-18**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0716.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407160-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407160-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407160-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Bổ sung XML13

- ![](https://i.imgur.com/d57JB4C.png)

- 🐛: XML01.CHAN_DOAN_VAO (không lấy được khi phòng đầu tiên chưa khám)

- ![](https://i.imgur.com/eLOaYJu.png)

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/494

- ☑: https://github.com/dh-hos/To_Ho_Tro/issues/20

- ☑: https://github.com/dh-hos/To_Trien_Khai/issues/57

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/77

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/489

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Đã ok !
