### ISSUE TITLE
Lỗi - Lấy sai mã đối tượng khám chữa bệnh XML1 (MA_DOITUONG_KCB) với bệnh nhân nhập viện trái tuyến tại BV tuyến tỉnh

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitaladmin#78]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbdalieuct_diachi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/hjZHtUwdx)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024035294` - _**MaKB**_: `MaKB` - _**MaBA**_: `001909` _**NgayKCB**_: `19/07/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `02` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

Những bệnh nhân nhập viện trái tuyến tại bệnh viện tuyến tỉnh (Không có giấy chuyển tuyến) theo mô tả hệ thống với mã loại Đối tượng KCB 3.2 như hình dưới
![image](https://github.com/user-attachments/assets/ffe0acbc-09cf-4f8a-8aeb-95d38c099af0)
Hiện tại khi xuất hoặc gởi XML4750 admin lại lấy (MA_DOITUONG_KCB) =9 nên sai so với mô tả.

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-23**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### Nhờ kiểm tra lại trường hợp này, không thỏa điều kiện 3.2
![image](https://github.com/user-attachments/assets/21016686-e535-460e-b803-eb9a81e8a134)

**Comment by hvtuan1987** [comment]
Em có set thử nếu tuyến =1 là Admin lấy MA_DOITUONG_KCB là 3.5 Nên cũng sai luôn á.
Anh coi lại dùm em chổ này trước.

**Comment by ongtrieuhau-dh** [comment]
### Nhờ check lại, bnnoitru.tuyen=1
![](https://i.imgur.com/9YJQMdd.png)

**Comment by hvtuan1987** [comment]
Này á !
![image](https://github.com/user-attachments/assets/d6df7b4e-740b-4e26-b791-1591a16f50ef)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0719.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407190-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407190-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407190-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛:

Lỗi - Lấy sai mã đối tượng khám chữa bệnh XML1 (MA_DOITUONG_KCB) với bệnh nhân nhập viện trái tuyến tại BV tuyến tỉnh

![](https://i.imgur.com/QyFqKHB.png)

- 🐛: Xử lý đơn giá thuốc (DON_GIA, DON_GIA_BV, DON_GIA_BH), vtyt lấy giabhyt khi giabhyt>0 (không thuộc thanh toán Stent)

- ![](https://i.imgur.com/kKOpa7P.png)

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/78

- ☑: https://github.com/dh-hos/To_Ho_Tro/issues/20

- ☑: https://github.com/dh-hos/To_Trien_Khai/issues/57

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Đã ok !
![image](https://github.com/user-attachments/assets/dddd89dc-fb2c-4961-b404-70f1244990f4)
