### ISSUE TITLE
Lỗi - Mô tả sai mã đối tượng KCB với trường hợp bệnh nhân tuyến xã nhập viện BV tuyến tỉnh không có giấy chuyển tuyến

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitaladmin#80]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbdalieuct_diachi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/hjZHtUwdx)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024035303` - _**MaKB**_: `2407000010` - _**MaBA**_: `000003` _**NgayKCB**_: `23/07/2024` - _**MaPhong**_: `` - _**MaDV**_: `02` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

Bệnh nhân ban đầu là nhập đối tượng Thu phí sau khi khám xong bác sĩ xử trí nhập viện. Bệnh nhân vào điều trị nội trú và xuất trình BHYT. Thẻ BHYT của bệnh nhân lúc này đăng ký tại tuyến xã và nhập viện tại Bệnh viện tuyến tỉnh. Khi chỉnh Đối tượng tại Treatment từ THU PHÍ sang BHYT Có hỏi bệnh nhân có giấy chuyển tuyến hoặc Cấp cứu Không. Chọn không và Treatment ghi nhận cột tuyen=0 

Theo mô tả hiện tại Admin lấy mã đối tượng Khám chữa bệnh =9 (Nên sai so với quyết định 627)
![image](https://github.com/user-attachments/assets/ffe0acbc-09cf-4f8a-8aeb-95d38c099af0)
Nhờ tổ code mô trả lại trường hợp này:
MA_DOITUONG_KCB = 3.2
-	Bnnoitru.tuyenbv = 3 
-	Bnnoitru.tuyen = 0
-	Bnnoitru.madkbd <> Bnnoitru.mabvkb
(Nếu đúng Thì lúc này mã đối tượng KCB phải =3.2)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-29**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vinh-dh 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Xem sai ở mô tả hay do chỗ nhập thông tin Treatment bị sai, để điều chỉnh lại.

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận
👉 Xác nhận trường hợp này là sai mô tả. Thực hiện điều chỉnh mô tả [xml130.checkin](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang00checkin%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md) và [xml130.bang1](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang01%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md).
⌛ Thời gian hoàn thành dự kiến: 2024-07-26

**Comment by vinh-dh** [comment]
Cập nhật mô tả [xml130.checkin](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang00checkin%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md): Bảng chỉ tiêu dữ liệu về trạng thái khám bệnh, chữa bệnh (Bảng check-in).
- Thay đổi ghi nhận giá trị ưu tiên cột  `ma_doituong_kcb` đối với giá trị `3.2`.

**Comment by ongtrieuhau-dh** [comment]
## 📣📣❓❓XÁC NHẬN MÔ TẢ CHỨC NĂNG MỚI, CHỈNH LỖI

- 📘 Nhờ GĐ: @nghivanbi **_xem xét, góp ý luồng mô tả này_**
- 📙 Nhờ TT.HT, TT.TK: @le-an-87, @lqbinh1987 **_xem xét, góp ý luồng mô tả này_**
- 📄 Thông tin kèm theo **__**
- 📢 Lưu ý: **_sau 2 giờ không phản hồi xem Tổ CODE sẽ thực hiện theo luồng mô tả_**

**Comment by vinh-dh** [comment]
Cập nhật mô tả [xml130.bang1](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang01%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md): Chỉ tiêu tổng hợp khám bệnh, chữa bệnh.
- Thay đổi ghi nhận giá trị ưu tiên cột  `ma_doituong_kcb` đối với giá trị `3.2`.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0726.4 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407264-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407264-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407264-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix: Lỗi - Mô tả sai mã đối tượng KCB với trường hợp bệnh nhân tuyến xã nhập viện BV tuyến tỉnh không có giấy chuyển tuyến

- ![](https://i.imgur.com/oieNqHi.png)

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/80

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @hvtuan1987 , do dữ liệu trên không có thông tin của maba: `000003`, nên không thực hiện kiểm thử trước được.

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @hvtuan1987 , @lqbinh1987 , @nghivanbi

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận** 
Đã thực hiện mô tả đúng theo luồng công việc này.
