### ISSUE TITLE
Lỗi - XML1 và XML 13 không lấy được Cột PHƯƠNG PHÁP ĐIỀU TRỊ của Khám bệnh ngoại trú

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitaladmin#82]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **31/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77156`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Phòng khám Phúc Gia Khang BRVT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_phucgiakhang_xml13`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023005832` - _**MaKB**_: `2407003320` - _**MaBA**_: `MaBA` _**NgayKCB**_: `30/07/2024` - _**MaPhong**_: `KB9` - _**MaDV**_: `02.03` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

Bảng XML1 không lấy được Phương pháp điều trị (Hình dưới)
![image](https://github.com/user-attachments/assets/0d7e11d6-faf2-479c-bac9-5ae7eb2275c7)

Bảng XML 13 không lấy được cột PHƯƠNG PHÁP ĐIỀU TRỊ và TÓM TẮT KẾT QUẢ .
Bệnh nhân có chuyển tuyến nhưng không có chỉ định cận lâm sàng.
(Hình phía dưới)
![image](https://github.com/user-attachments/assets/cc57dc64-e6c5-43f5-9695-58e079e5b5a5)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-02**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## 📣📣❓❓XÁC NHẬN MÔ TẢ CHỨC NĂNG MỚI, CHỈNH LỖI

- 📘 Nhờ GĐ: @nghivanbi **_xem xét, góp ý luồng mô tả này_**
- 📙 Nhờ TT.HT, TT.TK: @le-an-87, @lqbinh1987, @hvtuan1987  **_xem xét, góp ý luồng mô tả này_**
- 📄 Thông tin kèm theo **__**

**1. PP_DIEU_TRI: sẽ lấy theo mô tả sau** 
![image](https://github.com/user-attachments/assets/fb6abdd9-4c65-4a6e-88e3-82ca8529108f)
**2. TOMTAT_KQ: Hiện tại không bắt buộc, nên ngoại trú sẽ không đưa lên thông tin này** 
![image](https://github.com/user-attachments/assets/13d156a3-7d15-454b-9c48-31c36e9f3454)


- 📢 Lưu ý: **_sau 2 giờ không phản hồi xem Tổ CODE sẽ thực hiện theo luồng mô tả_**

**Comment by hvtuan1987** [comment]
@ongtrieuhau-dh Với XML13 trường Tóm tắt kết quả nếu bệnh nhân không có cls thì anh để chuổi mặc định là "Không" đi á ! Vì ngay đó cổng không cho rỗng á !

**Comment by ongtrieuhau-dh** [comment]
- ❓Hiện tại cổng đang bắt rỗng à, sao theo mô tả thì chỗ này không bắt buộc mà hoặc có hướng dẫn hay những thông tin bắt buộc gì hông, để CODE biết mà mô tả bổ sung nhé @hvtuan1987

**Comment by nghivanbi** [comment]
> @ongtrieuhau-dh Với XML13 trường Tóm tắt kết quả nếu bệnh nhân không có cls thì anh để chuổi mặc định là "Không" đi á ! Vì ngay đó cổng không cho rỗng á !

Có hình cổng báo không cho rỗng không? Có thì gởi lên để thuyết phục hơn.

**Comment by hvtuan1987** [comment]
@nghivanbi Dạ để nhờ đơn vị kiếm lại á !
Theo quy định thì trường này bỏ lại hong bắt buộc
![image](https://github.com/user-attachments/assets/2b2df61d-91b8-4f19-8e5e-ebd68595c4e1)

**Comment by ongtrieuhau-dh** [comment]
Cho xin file này nhé @hvtuan1987

**Comment by hvtuan1987** [comment]
@ongtrieuhau Em gởi á !
https://gofile.me/78TQg/i81BQMuRo
Filie 4750 sắp tới thay đổi luôn á  ! 
https://gofile.me/78TQg/wZCOCjmOa

**Comment by hvtuan1987** [comment]
Trường Phươg pháp điều trị đã lấy được. Sau khi hỏi lại đơn vị Cột Tóm tắt kết quả cổng không bắt theo mô tả nên XML13 đã ok 
![image](https://github.com/user-attachments/assets/af470011-7ed2-454a-b59c-91532f1eefad)
