### ISSUE TITLE
Lỗi - Admin Khi thêm nhân viên mới

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitaladmin#83]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **31/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất Cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_phucgiakhang_xml13`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/vblZPGoQE)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

Vào Module Admin  Bấm Thêm-> Nhập các thông tin sau đó bấm Lưu lại báo Lỗi như Hình dưới

![image](https://github.com/user-attachments/assets/d7d1f332-3efb-4e0a-9126-36f727a1c41c)

Chi tiết lỗi
Phiên bản :2024.07.30.021630AM
Npgsql.NpgsqlException:
INSERT has more expressions than target columns
Severity: ERROR
Code: 42601
   at HosAdmin.Adapter.NhanVienAdapter.InsertV2(String pMaNV, String pHolot, String pTen, String ptaiKhoan, String pMatKhau, String pDiaChi, String pDienThoaiNB, String pMobile, String pDienthoaiR, String pEmail, Object pLoaiNV, Object pMaCV, Object pMaTD, Object pMaCK, Object pMaDV, Object pTrangThai, String pAnh, String pDuocKham, Int32 iGioiTinh, String pMaNVNB, String pMa_Medisoft, String pMaCV2348, String pSobhxh, String pHolot_thuan, DateTime ngaysinh, String cmnd, String api_bhxh_username, String api_bhxh_password, Int32 api_bhxh_donvi, Int32 api_bhxh_benhvien, Boolean thuchien)
   at HosAdmin.Forms.FrmDmNhanVien.buttonclick(Object sender, EventArgs e)
  INSERT INTO   current.dmnhanvien                (manv, holot, ten, taikhoan, matkhau, diachi, dienthoainb,                mobile, dienthoair, email, chuky, loai,                macv, matd, mack, madv, icd, trangthai, duockham, manvnb, gioitinh, ma_medisoft, macc_hanhnghe_cv2348, sobhxh, holot_thuan,                ngaysinh, cmnd, api_bhxh_username, api_bhxh_password, api_bhxh_donvi, api_bhxh_benhvien)  VALUES        ((('048')::varchar), (('Ha Anh')::varchar), (('Tuan')::varchar), (('ha')::varchar), (('202cb962ac59075b964b07152d234b70')::varchar), (('')::varchar), (('')::varchar),                (('')::varchar), (('')::varchar), (('')::varchar),  decode((('/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAYABkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9/KKKKACiiigAooooAKKKKAP/2Q==')),'base64'),  (('00')::varchar),                (('00')::varchar), (('00')::varchar), (('00')::varchar), (('02.03')::varchar), null, (('1')::varchar), (('1')::varchar), (('')::varchar), ((0)::numeric), (('')::varchar), (('')::varchar), (('')::varchar),(('')::varchar),                ((NULL)::date), (('')::varchar), (('')::varchar), (('')::varchar), ((0)::numeric), ((0)::numeric), ((0)::numeric));  INSERT INTO   current.mknhanvien                (manv, ngaychange, matkhau)  VALUES        ((('048')::varchar), current_timestamp, (('202cb962ac59075b964b07152d234b70')::varchar));

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-05**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0801.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408010-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408010-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408010-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - Admin Khi thêm nhân viên mới ![](https://i.imgur.com/YTOP4MY.png)

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/83

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Đã ok !
