### ISSUE TITLE
Lỗi - TEST - HIỆU CHỈNH THÔNG TIN NGOẠI TRÚ CHECK BN LAO KHÔNG GÁN psdangky.trangthaichuyentuyen = 5

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitaladmin#89]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Ninh Kiều**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_ninhkieu_full`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/RZlAHjig7)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000202` - _**MaKB**_: `2407000075` - _**MaBA**_: `MaBA` _**NgayKCB**_: `20/08/2024` - _**MaPhong**_: `06` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

[HIỆU CHỈNH THÔNG TIN NGOẠI TRÚ CHECK BN LAO KHÔNG GÁN psdangky.trangthaichuyentuyen = 5
](https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/108#issuecomment-2295563140)
Khi đăng ký khám bệnh không check BN Lao

![image](https://github.com/user-attachments/assets/c0842f14-6da0-4ad8-a0de-13a9c770f96d)

Vào Hiệu chỉnh thông tin ngoại trú > Hiệu chỉnh Check BN Khám Lao > Trạng thái Chuyển tuyến không tự gán: Giấy hẹn lĩnh thuốc (psdangky.trangthaichuyentuyen = 5)

![image](https://github.com/user-attachments/assets/491f7ee7-813a-4bc6-acbe-94dd49c25775)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-22**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**:  @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Xem có chỉnh phần code này trong form Hiệu chỉnh thông tin chưa nhé?

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-08-22.

**Comment by le-an-87** [comment]
- ⌛ Chuyển tiếp nhóm Coder: @ongtrieuhau-dh 
- Lý do: cá nhân test theo git https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/105.
***

**Comment by minhduc2it** [comment]
Hiệu chỉnh thông tin ngoại trú
**1.** Chức năng TT Mở rộng và Chuyển tuyến > 2 chức năng này đang giống nhau > Hiển thị 1 chức năng cho ngưới dùng tiện sử dụng
![image](https://github.com/user-attachments/assets/bf5dd736-db89-407c-a6ef-f0b517acf8f5)

**2.** Tab Chuyển tuyến bị thiếu thông tin: **Nơi giới thiệu và Chẩn đoán**
![image](https://github.com/user-attachments/assets/03b5fa45-307d-4595-8ef8-006db274afb9)

**3.** Tab Thông tin thêm thiếu thông tin: Check Giấy xác nhận Lưu trú và Chọn Giấy Lưu
![image](https://github.com/user-attachments/assets/b24ad024-84f8-4124-9634-9b232068a675)

**Comment by lequocthong29** [comment]
@minhduc2it Nơi giới thiệu, Chẩn đoán hiện đã có sẳn trên form rồi mà a. Đặt nút chuyển tuyến ở đó để người dùng nhập nơi giới thiệu, chẩn đoán xong dễ dàng nhập thêm các thông tin khác.
![image](https://github.com/user-attachments/assets/d1d7f3a8-2e41-41bb-bcf7-ba64888c67aa)

**Comment by minhduc2it** [comment]
> @minhduc2it Nơi giới thiệu, Chẩn đoán hiện đã có sẳn trên form rồi mà a. Đặt nút chuyển tuyến ở đó để người dùng nhập nơi giới thiệu, chẩn đoán xong dễ dàng nhập thêm các thông tin khác. ![image](https://private-user-images.githubusercontent.com/110148171/359355234-d1d7f3a8-2e41-41bb-bcf7-ba64888c67aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzQyOTksIm5iZiI6MTcyNDEzMzk5OSwicGF0aCI6Ii8xMTAxNDgxNzEvMzU5MzU1MjM0LWQxZDdmM2E4LTJlNDEtNDFiYi1iY2Y3LWJhNjQ4ODhjNjdhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNjA2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTkxN2M2NzBiMjBjYzZjMDczZDZiYmRlODFiY2VjZjNjNGU1ZWNhNGNkYzVmNjQ4NDU1ZmE3NGI0MjUwN2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DCOKzyN0rPWyOv1BO3i9wvG2fgLm3jI6gvHnBmJf5RM)

Ok @lequocthong29, Đã nắm ý nghĩa chỗ chuyển tuyến

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0821.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32408210-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32408210-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32408210-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - Hiệu chỉnh thông tin chưa hỗ trợ tự lấy trạng thái chuyển tuyến = 5(Giấy hẹn lãnh thuốc) khi check bệnh nhân khám lao

- 🐛: Fix - Thiếu thông tin Check giấy xác nhận lưu trú và chọn giấy lưu ở tab Thông tin thêm

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/89

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/105

![](https://i.imgur.com/HU06FFQ.png)

![](https://i.imgur.com/aVn0Vhd.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---

1. Đã Kiểm tra Hiệu chỉnh thông tin ngoại trú trên Admin: Check Khám Lao hoàn thành

![image](https://github.com/user-attachments/assets/ebd13f3d-9c26-42b6-8392-f738a9dac33d)

2. Đã Kiểm tra Hiệu chỉnh thông tin ngoại trú trên Admin: Check Giấy xác nhận cư trú hoàn thành

![image](https://github.com/user-attachments/assets/8301ae08-943e-4767-ba43-c42fdcf0f05e)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0821.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408210-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408210-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408210-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - Hiệu chỉnh thông tin chưa hỗ trợ tự lấy trạng thái chuyển tuyến = 5(Giấy hẹn lãnh thuốc) khi check bệnh nhân khám lao

- 🐛: Fix - Thiếu thông tin Check giấy xác nhận lưu trú và chọn giấy lưu ở tab Thông tin thêm

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/89

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
Báo thêm cập nhật chức năng Check khám Lao và Check Giấy Lưu của 2 module:

**1. Precsription: trên Hiệu chỉnh thông tin** 
![image](https://github.com/user-attachments/assets/61ad758c-fbbd-4f60-a6b4-3ea7ba783fa4)

**3. Printer: trên Chỉnh thông tin trên From in Phiếu 01**
![image](https://github.com/user-attachments/assets/2ea13501-cc8f-4f33-a990-8eb7138abb16)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0821.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408210-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408210-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408210-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **Chỉnh lỗi**: **_Lỗi - TEST - HIỆU CHỈNH THÔNG TIN NGOẠI TRÚ CHECK BN LAO KHÔNG GÁN psdangky.trangthaichuyentuyen = 5_**

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/89

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @minhduc2it , @le-an-87

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
**1. Precsription: trên Hiệu chỉnh thông tin** 
**- Check khám Lao**
![image](https://github.com/user-attachments/assets/5511b16c-c4f8-47c3-878d-5b5863a5964a)

**- Check Giấy Lưu**
![image](https://github.com/user-attachments/assets/966dedda-43ab-4521-a4e1-7bf3926a9cb5)

**2. Printer: trên Chỉnh thông tin trên From in Phiếu 01**
**- Check Khám Lao**
![image](https://github.com/user-attachments/assets/54e08720-05d5-4766-a20e-a5ba49ca1aea)

**- Check Giấy Lưu**
![image](https://github.com/user-attachments/assets/69f09620-0545-4211-aa9c-af4265bfab52)


Các chức năng khác: Đăng ký, khám bệnh, in phiếu 01 chưa ghi nhận bất thường
![image](https://github.com/user-attachments/assets/6c71dbf2-d1a9-41c5-af24-8016d41f354b)
