### ISSUE TITLE
Lỗi - XUẤT XML 4750 THIẾU T_BNTT CỦA VTYT

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitaladmin#90]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP CẦN THƠ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dktpct_022956`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/jvcCeUgUU)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024049135` - _**MaKB**_: `MaKB` - _**MaBA**_: `022956` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `22` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- XML1.T_BNTT và XML3.T_BNTT thiếu chi phí của VTYT có áp giá BHYT
![image](https://github.com/user-attachments/assets/66345942-5940-485d-b7eb-edc8d744c94b)
![image](https://github.com/user-attachments/assets/2aa2ff8c-7578-49b8-91b8-4d250838d5ed)
- Em đã chọn thử option và xuất thử lại thì cả 2 tuỳ chọn đều không lấy theo giá đúng để thể hiện đầy đủ T_BNTT
![image](https://github.com/user-attachments/assets/238b9181-b719-439f-b965-084943374d76)
![image](https://github.com/user-attachments/assets/7cbb3090-f7ef-4965-9724-bd1856a6c5da)

Check dùm em các loại thuốc và VTYT có áp giá BHYT để lấy đầy đủ T_BNTT 
hiện đơn vị đang tồn động hơn 20 hồ sơ chờ fix để thay thế.

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-23**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## 📣📣❓❓XÁC NHẬN CHỨC NĂNG

- 📘 Nhờ GĐ: @nghivanbi **_xem xét, góp ý luồng mô tả này_**
- 📙 Nhờ TT.HT, TT.TK:  @nqhoa1005  @lqbinh1987 **_xem xét, góp ý luồng mô tả này_**
- 📄 Thông tin kèm theo:

1. **Lý do phải gửi tiền chênh lệch này lên cổng BHXH**
2. **Với cấu hình hiện tại tham khảo bệnh viện và cổng giám định sẽ GHI các trường dưới đây như thế nào ở các trường:**

- **pshdxn.dongia=98,000,000**
- **pshdxn.giabhyt = 70,000,000**
- **dmthuoc.tyle = 0**
- **dmthuoc.tyle_tt = 100**
👉❓
- DON_GIA_BV = ❓ 
- DON_GIA_BH = ❓
- TYLE_TT_DV  = ❓
- TYLE_TT_BH = ❓

**Nguyên nhân phải xác định lại các giá trị này là phải thực hiện theo công thức check của cổng:** 

- THANH_TIEN_BV = SO_LUONG * DON_GIA_BV * TYLE_TT_DV
- THANH_TIEN_BH = SO_LUONG * DON_GlA_BH * TYLE_TT_DV/100 * TYLE_TT_BH/100

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0821.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408211-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408211-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408211-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **Chỉnh lỗi**: **_Lỗi - XUẤT XML 4750 THIẾU T_BNTT CỦA VTYT_**

- ✨: Đối với VTYT (không thuộc stent): TYLE_TT_DV=100, TYLE_TT_BH =100

- XML03.DON_GIA_BH = nếu pshdxn.giabhyt > 0 lấy pshdxn.giabhyt ngược lại pshdxn.dongia

- XML03.DON_GIA_BV = pshdxn.dongia,

- Trường hợp sử dụng chức năng (option) DON_GIA_BV là DON_GIA_BH (XML03.DON_GIA_BV = XML03.DON_GIA_BH)

- ✨: Đối với THUỐC (không thuộc stent): TYLE_TT_DV=100, TYLE_TT_BH =100

- XML02.DON_GIA = nếu pshdxn.giabhyt > 0 lấy pshdxn.giabhyt ngược lại pshdxn.dongia,

- ![](https://i.imgur.com/Rc8shLM.png) ![](https://i.imgur.com/wVMqN63.png)

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/90

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
Đã fix
![image](https://github.com/user-attachments/assets/acd63454-f4b5-4c30-92fa-d544b6946ad7)
![image](https://github.com/user-attachments/assets/b3e9d05b-de71-4c46-9cb3-8bff1437814f)
