### ISSUE TITLE
Lỗi - VTYT lấy sai DON_GIA_BV trên XML03 Trường hợp sử dụng chức năng (option) DON_GIA_BV là DON_GIA_BH

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaladmin#94]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hồng Ngự**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_hongngu_xml3_giavattutheocauhinh_09092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/wuEnvyPOL)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011864` - _**MaKB**_: `2408012189` - _**MaBA**_: `2024013351` _**NgayRV**_: `22/8/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `02` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `TH118` - _**SoHD**_: `G04.X24.0822.114814` - _**NgayHD**_: `22/8/2024` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

DON_GIA_BV của VTYT trên XML03 không lấy theo cấu hình DON_GIA_BV là DON_GIA_BH (XML03.DON_GIA_BV = XML03.DON_GIA_BH)
- Bệnh nhân có sử dụng vật tư có giá BH khác giá xuất khi cấu hình DON_GIA_BV là DON_GIA_BH thì phần mềm không lấy theo mô tả của Admin 

![ảnh](https://github.com/user-attachments/assets/00fc1e8f-5e98-4337-baec-2da32a63693f)
![ảnh](https://github.com/user-attachments/assets/bbe0c16e-f9a7-43c7-badb-89a0a554fdf8)
![ảnh](https://github.com/user-attachments/assets/21a53ee9-20f3-4dbe-8d81-2ca17ff2b019)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-16**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0911.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409113-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409113-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409113-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - VTYT lấy sai DON_GIA_BV trên XML03 Trường hợp sử dụng chức năng (option) DON_GIA_BV là DON_GIA_BH_**

- 🐛: Xử lý DON_GIA_BV theo cấu hình trên Admin ![](https://i.imgur.com/wca7ckz.png)

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/94

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '  18/09/2024  '.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm HospitalAdmin.exe v.3.24.0912.0
***
>Lỗi, yêu cầu đã hoàn thành 

- Nội dung: 

  - Admin mới đã fix lỗi VTYT lấy sai DON_GIA_BV trên XML03 Trường hợp sử dụng chức năng (option) DON_GIA_BV là DON_GIA_BH

- Hình ảnh: 

  - Không sử dụng cấu hình DON_GIA_BV là DON_GIA_BH
  ![ảnh](https://github.com/user-attachments/assets/7cb611c7-9371-4ed7-9b4b-48904ff50ea8)
  ![ảnh](https://github.com/user-attachments/assets/4daf8eec-e5e1-413b-9201-5bc531afe38b)
  ![ảnh](https://github.com/user-attachments/assets/ed43d9e9-618c-427a-a3e6-8ea5c69a207b)


  - Sử dụng cấu hình DON_GIA_BV là DON_GIA_BH  
![ảnh](https://github.com/user-attachments/assets/5a6a4f56-1543-4aff-a783-0f3c1c1a3b36)
![ảnh](https://github.com/user-attachments/assets/7aeb72ae-2665-4f72-9700-ceda4162f857)
![ảnh](https://github.com/user-attachments/assets/a1a63e0e-c04e-4a5a-9cb8-b99bda88c41a)





***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

>- Diễn giải lỗi:


>- Hình ảnh lỗi:



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Hoàn Thành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
