### ISSUE TITLE
Lỗi - BANT ĐỢT LẤY 2 DÒNG KHI XUẤT 4750 

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitaladmin#97]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `192.168.50.99/hoa_thanhtri_full`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/dWd6aMUws)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018004732` - _**MaKB**_: `2408000208` - _**MaBA**_: `N2024002321` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BANT đợt khi lập mới mặc định khambenh sẽ có 2 dòng
![image](https://github.com/user-attachments/assets/69325ddb-7cbb-4e4e-a77c-83de5c3bf1df)

khi kết thúc phát sinh 1 số trường hợp sinh ra XML cả 2 dòng khi lấy lên 4210 và 4750 đều có ca trùng gây lệch tổng số lượng hồ sơ XML

Xuất từ 4750 Admin
![image](https://github.com/user-attachments/assets/143c1597-0404-4a33-bbb2-f2ee66c0797e)

Xuất từ 4210 Report
![image](https://github.com/user-attachments/assets/6b688e2b-c3fa-4a2e-912a-47811d913da0)

khi xem chi phí thì toàn bộ được thanh theo BANT nên Admin và Report đang lấy lên dư dòng không có maba trong bảng khambenh.

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ❌ **Từ chối tiếp nhận** 
- 📣 **Nguyên nhân**: _IP mới không nằm trong luồng công việc trước giờ, không cung cấp tài khoản, mật khẩu_


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.] Nghĩa vụ: ghi nhận vi phạm nếu có tại HD.04, phản hồi
đủ thông tin

**Comment by nqhoa1005** [comment]
vậy là không tiếp nhận IP mới hay cần bổ sung Tài khoản và Mật Khẩu anh @ongtrieuhau

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- Thì phải cung cấp các thông tin kết nối mới kiểm thử được chứ, giờ hông biết kết nối thế nào, thì kiểm tra sao đây.

**Comment by nqhoa1005** [comment]
ℹ️ Thông tin kết nối :
IP : 192.168.50.60
Port : 5432
Tên Dữ liệu :  hoa_thanhtri_full
Tài khoản : Postgres
Mật Khẩu : 123
----------------
 Em bổ sung thông tin, check giúp em nha

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-23**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by nqhoa1005** [comment]
✔️ **ĐÃ TIẾP NHẬN** 
👉 **Vui lòng chờ test lại**

**Comment by nqhoa1005** [comment]
✅ Đã fix
![image](https://github.com/user-attachments/assets/89443c79-2644-48ef-9ba0-5a0d23087344)
![image](https://github.com/user-attachments/assets/f4c791a8-97a5-4f53-80ee-aa0606330880)

4210 vẫn còn 2 dòng > đóng Git chuyển sang báo lỗi 4210 trên Report
![image](https://github.com/user-attachments/assets/600df463-b3e6-4261-9dde-35750eec7e99)
