### ISSUE TITLE
Lỗi - Ghi nhận sai mã liên kết

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaladmin#98]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Phước Long**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbphuoclong_bli_sai_malk`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/6znBETjZh)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023020943` - _**MaKB**_: `2406011780` - _**MaBA**_: `2024005731` _**NgayKCB**_: `08/07/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `05` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trong mã liên kết chưa mã bn không phải của BN đó, như hình dưới BN có mã bn là 2023020943, nhưng trong mã liên kết lại có chứa Mã BN 95006_2024_07_```2023020743```_2406011780_2024005731.
Tương tự đối với mã khám bệnh cũng vậy, Bn có mã khám là 2407000921, nhưng trong mã liên kết lại chứa 95006_2024_07_2018050522_```2407000721```_2024005854.

![image](https://github.com/user-attachments/assets/de98ff8c-4dc5-45d2-98ef-bda3d8294955)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-30**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @lqbinh1987 . 
- Hướng xử lý: Xóa các MA_LK bị sai trong bảng current.psxml -> Dùng Admin phiên bản mới nhất xem còn bị trình trạng này nữa hông.
- Kiểm thử lại quá trình xuất viện, trả về điều trị, chỉnh tháng ra viện bằng Treatment, Admin mới nhất xem còn tình trạng này nữa hông.
- Kiểm soát theo luồng công việc này: https://github.com/dh-hos/To_Lap_Trinh/issues/628

**Comment by lqbinh1987** [comment]
✅Hiện tại trong quá trình treo dõi tại đơn vị, và chạy tool **Kiểm tra và cập nhật hồ sơ XML130** thì đã xữ lý được trường hợp sai mã liên kết của git này.
![image](https://github.com/user-attachments/assets/70b37ff3-5ae5-4cea-8ba9-bf551b001e20)

- Và Tổ triển Khai cũng đã cơ bản kiểm soát được các theo tác gây lệch XML, thiếu XML tại các git này
https://github.com/dh-hos/dhg.hospitalprescription/issues/345
https://github.com/dh-hos/To_Lap_Trinh/issues/688
https://github.com/dh-hos/dhg.hosptaltreatment/issues/276
https://github.com/dh-hos/dhg.hospitalprescription/issues/349
